/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioToolsRouteImport } from './routes/audio-tools'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImageToolsRouteImport } from './routes/image-tools'
import { Route as PdfToolsRouteImport } from './routes/pdf-tools'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TranslationToolsRouteImport } from './routes/translation-tools'
import { Route as VideoToolsRouteImport } from './routes/video-tools'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as FileTypesIndexRouteImport } from './routes/file-types/index'
import { Route as FileTypesSlugRouteImport } from './routes/file-types/$slug'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsSlugRouteImport } from './routes/questions/$slug'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ToolsAgeCalculatorRouteImport } from './routes/tools/age-calculator'
import { Route as ToolsBackgroundRemoverRouteImport } from './routes/tools/background-remover'
import { Route as ToolsBarcodeGeneratorRouteImport } from './routes/tools/barcode-generator'
import { Route as ToolsBase64EncoderRouteImport } from './routes/tools/base64-encoder'
import { Route as ToolsBase64ImageEncoderRouteImport } from './routes/tools/base64-image-encoder'
import { Route as ToolsBinaryConverterRouteImport } from './routes/tools/binary-converter'
import { Route as ToolsBmiCalculatorRouteImport } from './routes/tools/bmi-calculator'
import { Route as ToolsCaseConverterRouteImport } from './routes/tools/case-converter'
import { Route as ToolsColorConverterRouteImport } from './routes/tools/color-converter'
import { Route as ToolsCreditCardValidatorRouteImport } from './routes/tools/credit-card-validator'
import { Route as ToolsCronParserRouteImport } from './routes/tools/cron-parser'
import { Route as ToolsCssGradientGeneratorRouteImport } from './routes/tools/css-gradient-generator'
import { Route as ToolsCsvToJsonConverterRouteImport } from './routes/tools/csv-to-json-converter'
import { Route as ToolsCurrencyConverterRouteImport } from './routes/tools/currency-converter'
import { Route as ToolsDateCalculatorRouteImport } from './routes/tools/date-calculator'
import { Route as ToolsDiceRollerRouteImport } from './routes/tools/dice-roller'
import { Route as ToolsDiscountCalculatorRouteImport } from './routes/tools/discount-calculator'
import { Route as ToolsDuplicateCharacterFinderRouteImport } from './routes/tools/duplicate-character-finder'
import { Route as ToolsFlipCoinSimulatorRouteImport } from './routes/tools/flip-coin-simulator'
import { Route as ToolsHashCheckGeneratorRouteImport } from './routes/tools/hash-check-generator'
import { Route as ToolsHashGeneratorRouteImport } from './routes/tools/hash-generator'
import { Route as ToolsHexConverterRouteImport } from './routes/tools/hex-converter'
import { Route as ToolsHtmlEncoderDecoderRouteImport } from './routes/tools/html-encoder-decoder'
import { Route as ToolsHtmlMinifierRouteImport } from './routes/tools/html-minifier'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools/image-compressor'
import { Route as ToolsImageEnhancerRouteImport } from './routes/tools/image-enhancer'
import { Route as ToolsInvestmentCalculatorRouteImport } from './routes/tools/investment-calculator'
import { Route as ToolsJsonFormatterRouteImport } from './routes/tools/json-formatter'
import { Route as ToolsJsonToCsvConverterRouteImport } from './routes/tools/json-to-csv-converter'
import { Route as ToolsJsonValidatorRouteImport } from './routes/tools/json-validator'
import { Route as ToolsJwtDecoderRouteImport } from './routes/tools/jwt-decoder'
import { Route as ToolsLineCounterRouteImport } from './routes/tools/line-counter'
import { Route as ToolsListRandomizerRouteImport } from './routes/tools/list-randomizer'
import { Route as ToolsLoanCalculatorRouteImport } from './routes/tools/loan-calculator'
import { Route as ToolsLoremIpsumRouteImport } from './routes/tools/lorem-ipsum'
import { Route as ToolsLoremIpsumCustomizerRouteImport } from './routes/tools/lorem-ipsum-customizer'
import { Route as ToolsMd5GeneratorRouteImport } from './routes/tools/md5-generator'
import { Route as ToolsMorseCodeConverterRouteImport } from './routes/tools/morse-code-converter'
import { Route as ToolsNumberToWordsConverterRouteImport } from './routes/tools/number-to-words-converter'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools/password-generator'
import { Route as ToolsPasswordStrengthTesterRouteImport } from './routes/tools/password-strength-tester'
import { Route as ToolsPercentageCalculatorRouteImport } from './routes/tools/percentage-calculator'
import { Route as ToolsQrCodeGeneratorRouteImport } from './routes/tools/qr-code-generator'
import { Route as ToolsQrGeneratorRouteImport } from './routes/tools/qr-generator'
import { Route as ToolsRandomColorGeneratorRouteImport } from './routes/tools/random-color-generator'
import { Route as ToolsRandomIdGeneratorRouteImport } from './routes/tools/random-id-generator'
import { Route as ToolsRandomNameGeneratorRouteImport } from './routes/tools/random-name-generator'
import { Route as ToolsRandomNumberGeneratorRouteImport } from './routes/tools/random-number-generator'
import { Route as ToolsRandomPasswordGeneratorRouteImport } from './routes/tools/random-password-generator'
import { Route as ToolsRegexGeneratorRouteImport } from './routes/tools/regex-generator'
import { Route as ToolsRegexTesterRouteImport } from './routes/tools/regex-tester'
import { Route as ToolsRomanNumeralConverterRouteImport } from './routes/tools/roman-numeral-converter'
import { Route as ToolsSlugCheckerRouteImport } from './routes/tools/slug-checker'
import { Route as ToolsSlugGeneratorRouteImport } from './routes/tools/slug-generator'
import { Route as ToolsSqlFormatterRouteImport } from './routes/tools/sql-formatter'
import { Route as ToolsTemperatureConverterRouteImport } from './routes/tools/temperature-converter'
import { Route as ToolsTextDiffCheckerRouteImport } from './routes/tools/text-diff-checker'
import { Route as ToolsTextToSpeechRouteImport } from './routes/tools/text-to-speech'
import { Route as ToolsTimeZoneConverterRouteImport } from './routes/tools/time-zone-converter'
import { Route as ToolsTipCalculatorRouteImport } from './routes/tools/tip-calculator'
import { Route as ToolsTranslatorRouteImport } from './routes/tools/translator'
import { Route as ToolsUnitConverterRouteImport } from './routes/tools/unit-converter'
import { Route as ToolsUrlEncoderRouteImport } from './routes/tools/url-encoder'
import { Route as ToolsUrlParserRouteImport } from './routes/tools/url-parser'
import { Route as ToolsUuidGeneratorRouteImport } from './routes/tools/uuid-generator'
import { Route as ToolsVatCalculatorRouteImport } from './routes/tools/vat-calculator'
import { Route as ToolsWordCounterRouteImport } from './routes/tools/word-counter'
import { Route as ToolsWordFrequencyAnalyzerRouteImport } from './routes/tools/word-frequency-analyzer'
import { Route as ToolsXmlFormatterRouteImport } from './routes/tools/xml-formatter'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioToolsRoute = AudioToolsRouteImport.update({
  id: '/audio-tools',
  path: '/audio-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsRoute = ImageToolsRouteImport.update({
  id: '/image-tools',
  path: '/image-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsRoute = PdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationToolsRoute = TranslationToolsRouteImport.update({
  id: '/translation-tools',
  path: '/translation-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToolsRoute = VideoToolsRouteImport.update({
  id: '/video-tools',
  path: '/video-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FileTypesIndexRoute = FileTypesIndexRouteImport.update({
  id: '/file-types/',
  path: '/file-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileTypesSlugRoute = FileTypesSlugRouteImport.update({
  id: '/file-types/$slug',
  path: '/file-types/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsSlugRoute = QuestionsSlugRouteImport.update({
  id: '/questions/$slug',
  path: '/questions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAgeCalculatorRoute = ToolsAgeCalculatorRouteImport.update({
  id: '/tools/age-calculator',
  path: '/tools/age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBackgroundRemoverRoute = ToolsBackgroundRemoverRouteImport.update({
  id: '/tools/background-remover',
  path: '/tools/background-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBarcodeGeneratorRoute = ToolsBarcodeGeneratorRouteImport.update({
  id: '/tools/barcode-generator',
  path: '/tools/barcode-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64EncoderRoute = ToolsBase64EncoderRouteImport.update({
  id: '/tools/base64-encoder',
  path: '/tools/base64-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64ImageEncoderRoute = ToolsBase64ImageEncoderRouteImport.update({
  id: '/tools/base64-image-encoder',
  path: '/tools/base64-image-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBinaryConverterRoute = ToolsBinaryConverterRouteImport.update({
  id: '/tools/binary-converter',
  path: '/tools/binary-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBmiCalculatorRoute = ToolsBmiCalculatorRouteImport.update({
  id: '/tools/bmi-calculator',
  path: '/tools/bmi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCaseConverterRoute = ToolsCaseConverterRouteImport.update({
  id: '/tools/case-converter',
  path: '/tools/case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorConverterRoute = ToolsColorConverterRouteImport.update({
  id: '/tools/color-converter',
  path: '/tools/color-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCreditCardValidatorRoute =
  ToolsCreditCardValidatorRouteImport.update({
    id: '/tools/credit-card-validator',
    path: '/tools/credit-card-validator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCronParserRoute = ToolsCronParserRouteImport.update({
  id: '/tools/cron-parser',
  path: '/tools/cron-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCssGradientGeneratorRoute =
  ToolsCssGradientGeneratorRouteImport.update({
    id: '/tools/css-gradient-generator',
    path: '/tools/css-gradient-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCsvToJsonConverterRoute = ToolsCsvToJsonConverterRouteImport.update({
  id: '/tools/csv-to-json-converter',
  path: '/tools/csv-to-json-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCurrencyConverterRoute = ToolsCurrencyConverterRouteImport.update({
  id: '/tools/currency-converter',
  path: '/tools/currency-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDateCalculatorRoute = ToolsDateCalculatorRouteImport.update({
  id: '/tools/date-calculator',
  path: '/tools/date-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiceRollerRoute = ToolsDiceRollerRouteImport.update({
  id: '/tools/dice-roller',
  path: '/tools/dice-roller',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDiscountCalculatorRoute = ToolsDiscountCalculatorRouteImport.update({
  id: '/tools/discount-calculator',
  path: '/tools/discount-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDuplicateCharacterFinderRoute =
  ToolsDuplicateCharacterFinderRouteImport.update({
    id: '/tools/duplicate-character-finder',
    path: '/tools/duplicate-character-finder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsFlipCoinSimulatorRoute = ToolsFlipCoinSimulatorRouteImport.update({
  id: '/tools/flip-coin-simulator',
  path: '/tools/flip-coin-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashCheckGeneratorRoute = ToolsHashCheckGeneratorRouteImport.update({
  id: '/tools/hash-check-generator',
  path: '/tools/hash-check-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashGeneratorRoute = ToolsHashGeneratorRouteImport.update({
  id: '/tools/hash-generator',
  path: '/tools/hash-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHexConverterRoute = ToolsHexConverterRouteImport.update({
  id: '/tools/hex-converter',
  path: '/tools/hex-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHtmlEncoderDecoderRoute = ToolsHtmlEncoderDecoderRouteImport.update({
  id: '/tools/html-encoder-decoder',
  path: '/tools/html-encoder-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHtmlMinifierRoute = ToolsHtmlMinifierRouteImport.update({
  id: '/tools/html-minifier',
  path: '/tools/html-minifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageEnhancerRoute = ToolsImageEnhancerRouteImport.update({
  id: '/tools/image-enhancer',
  path: '/tools/image-enhancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsInvestmentCalculatorRoute =
  ToolsInvestmentCalculatorRouteImport.update({
    id: '/tools/investment-calculator',
    path: '/tools/investment-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsJsonFormatterRoute = ToolsJsonFormatterRouteImport.update({
  id: '/tools/json-formatter',
  path: '/tools/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonToCsvConverterRoute = ToolsJsonToCsvConverterRouteImport.update({
  id: '/tools/json-to-csv-converter',
  path: '/tools/json-to-csv-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonValidatorRoute = ToolsJsonValidatorRouteImport.update({
  id: '/tools/json-validator',
  path: '/tools/json-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJwtDecoderRoute = ToolsJwtDecoderRouteImport.update({
  id: '/tools/jwt-decoder',
  path: '/tools/jwt-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLineCounterRoute = ToolsLineCounterRouteImport.update({
  id: '/tools/line-counter',
  path: '/tools/line-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsListRandomizerRoute = ToolsListRandomizerRouteImport.update({
  id: '/tools/list-randomizer',
  path: '/tools/list-randomizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoanCalculatorRoute = ToolsLoanCalculatorRouteImport.update({
  id: '/tools/loan-calculator',
  path: '/tools/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoremIpsumRoute = ToolsLoremIpsumRouteImport.update({
  id: '/tools/lorem-ipsum',
  path: '/tools/lorem-ipsum',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoremIpsumCustomizerRoute =
  ToolsLoremIpsumCustomizerRouteImport.update({
    id: '/tools/lorem-ipsum-customizer',
    path: '/tools/lorem-ipsum-customizer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsMd5GeneratorRoute = ToolsMd5GeneratorRouteImport.update({
  id: '/tools/md5-generator',
  path: '/tools/md5-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMorseCodeConverterRoute = ToolsMorseCodeConverterRouteImport.update({
  id: '/tools/morse-code-converter',
  path: '/tools/morse-code-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNumberToWordsConverterRoute =
  ToolsNumberToWordsConverterRouteImport.update({
    id: '/tools/number-to-words-converter',
    path: '/tools/number-to-words-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/tools/password-generator',
  path: '/tools/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordStrengthTesterRoute =
  ToolsPasswordStrengthTesterRouteImport.update({
    id: '/tools/password-strength-tester',
    path: '/tools/password-strength-tester',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsPercentageCalculatorRoute =
  ToolsPercentageCalculatorRouteImport.update({
    id: '/tools/percentage-calculator',
    path: '/tools/percentage-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsQrCodeGeneratorRoute = ToolsQrCodeGeneratorRouteImport.update({
  id: '/tools/qr-code-generator',
  path: '/tools/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrGeneratorRoute = ToolsQrGeneratorRouteImport.update({
  id: '/tools/qr-generator',
  path: '/tools/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRandomColorGeneratorRoute =
  ToolsRandomColorGeneratorRouteImport.update({
    id: '/tools/random-color-generator',
    path: '/tools/random-color-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRandomIdGeneratorRoute = ToolsRandomIdGeneratorRouteImport.update({
  id: '/tools/random-id-generator',
  path: '/tools/random-id-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRandomNameGeneratorRoute =
  ToolsRandomNameGeneratorRouteImport.update({
    id: '/tools/random-name-generator',
    path: '/tools/random-name-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRandomNumberGeneratorRoute =
  ToolsRandomNumberGeneratorRouteImport.update({
    id: '/tools/random-number-generator',
    path: '/tools/random-number-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRandomPasswordGeneratorRoute =
  ToolsRandomPasswordGeneratorRouteImport.update({
    id: '/tools/random-password-generator',
    path: '/tools/random-password-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRegexGeneratorRoute = ToolsRegexGeneratorRouteImport.update({
  id: '/tools/regex-generator',
  path: '/tools/regex-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRegexTesterRoute = ToolsRegexTesterRouteImport.update({
  id: '/tools/regex-tester',
  path: '/tools/regex-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRomanNumeralConverterRoute =
  ToolsRomanNumeralConverterRouteImport.update({
    id: '/tools/roman-numeral-converter',
    path: '/tools/roman-numeral-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSlugCheckerRoute = ToolsSlugCheckerRouteImport.update({
  id: '/tools/slug-checker',
  path: '/tools/slug-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugGeneratorRoute = ToolsSlugGeneratorRouteImport.update({
  id: '/tools/slug-generator',
  path: '/tools/slug-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSqlFormatterRoute = ToolsSqlFormatterRouteImport.update({
  id: '/tools/sql-formatter',
  path: '/tools/sql-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTemperatureConverterRoute =
  ToolsTemperatureConverterRouteImport.update({
    id: '/tools/temperature-converter',
    path: '/tools/temperature-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsTextDiffCheckerRoute = ToolsTextDiffCheckerRouteImport.update({
  id: '/tools/text-diff-checker',
  path: '/tools/text-diff-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextToSpeechRoute = ToolsTextToSpeechRouteImport.update({
  id: '/tools/text-to-speech',
  path: '/tools/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTimeZoneConverterRoute = ToolsTimeZoneConverterRouteImport.update({
  id: '/tools/time-zone-converter',
  path: '/tools/time-zone-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTipCalculatorRoute = ToolsTipCalculatorRouteImport.update({
  id: '/tools/tip-calculator',
  path: '/tools/tip-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTranslatorRoute = ToolsTranslatorRouteImport.update({
  id: '/tools/translator',
  path: '/tools/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUnitConverterRoute = ToolsUnitConverterRouteImport.update({
  id: '/tools/unit-converter',
  path: '/tools/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUrlEncoderRoute = ToolsUrlEncoderRouteImport.update({
  id: '/tools/url-encoder',
  path: '/tools/url-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUrlParserRoute = ToolsUrlParserRouteImport.update({
  id: '/tools/url-parser',
  path: '/tools/url-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidGeneratorRoute = ToolsUuidGeneratorRouteImport.update({
  id: '/tools/uuid-generator',
  path: '/tools/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVatCalculatorRoute = ToolsVatCalculatorRouteImport.update({
  id: '/tools/vat-calculator',
  path: '/tools/vat-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWordCounterRoute = ToolsWordCounterRouteImport.update({
  id: '/tools/word-counter',
  path: '/tools/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWordFrequencyAnalyzerRoute =
  ToolsWordFrequencyAnalyzerRouteImport.update({
    id: '/tools/word-frequency-analyzer',
    path: '/tools/word-frequency-analyzer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsXmlFormatterRoute = ToolsXmlFormatterRouteImport.update({
  id: '/tools/xml-formatter',
  path: '/tools/xml-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/sitemap': typeof SitemapRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/barcode-generator': typeof ToolsBarcodeGeneratorRoute
  '/tools/base64-encoder': typeof ToolsBase64EncoderRoute
  '/tools/base64-image-encoder': typeof ToolsBase64ImageEncoderRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/credit-card-validator': typeof ToolsCreditCardValidatorRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-gradient-generator': typeof ToolsCssGradientGeneratorRoute
  '/tools/csv-to-json-converter': typeof ToolsCsvToJsonConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/date-calculator': typeof ToolsDateCalculatorRoute
  '/tools/dice-roller': typeof ToolsDiceRollerRoute
  '/tools/discount-calculator': typeof ToolsDiscountCalculatorRoute
  '/tools/duplicate-character-finder': typeof ToolsDuplicateCharacterFinderRoute
  '/tools/flip-coin-simulator': typeof ToolsFlipCoinSimulatorRoute
  '/tools/hash-check-generator': typeof ToolsHashCheckGeneratorRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-encoder-decoder': typeof ToolsHtmlEncoderDecoderRoute
  '/tools/html-minifier': typeof ToolsHtmlMinifierRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/investment-calculator': typeof ToolsInvestmentCalculatorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-csv-converter': typeof ToolsJsonToCsvConverterRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/line-counter': typeof ToolsLineCounterRoute
  '/tools/list-randomizer': typeof ToolsListRandomizerRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/lorem-ipsum-customizer': typeof ToolsLoremIpsumCustomizerRoute
  '/tools/md5-generator': typeof ToolsMd5GeneratorRoute
  '/tools/morse-code-converter': typeof ToolsMorseCodeConverterRoute
  '/tools/number-to-words-converter': typeof ToolsNumberToWordsConverterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/password-strength-tester': typeof ToolsPasswordStrengthTesterRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/random-color-generator': typeof ToolsRandomColorGeneratorRoute
  '/tools/random-id-generator': typeof ToolsRandomIdGeneratorRoute
  '/tools/random-name-generator': typeof ToolsRandomNameGeneratorRoute
  '/tools/random-number-generator': typeof ToolsRandomNumberGeneratorRoute
  '/tools/random-password-generator': typeof ToolsRandomPasswordGeneratorRoute
  '/tools/regex-generator': typeof ToolsRegexGeneratorRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/roman-numeral-converter': typeof ToolsRomanNumeralConverterRoute
  '/tools/slug-checker': typeof ToolsSlugCheckerRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/temperature-converter': typeof ToolsTemperatureConverterRoute
  '/tools/text-diff-checker': typeof ToolsTextDiffCheckerRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/tip-calculator': typeof ToolsTipCalculatorRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encoder': typeof ToolsUrlEncoderRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/tools/vat-calculator': typeof ToolsVatCalculatorRoute
  '/tools/word-counter': typeof ToolsWordCounterRoute
  '/tools/word-frequency-analyzer': typeof ToolsWordFrequencyAnalyzerRoute
  '/tools/xml-formatter': typeof ToolsXmlFormatterRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/file-types/': typeof FileTypesIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/sitemap': typeof SitemapRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/barcode-generator': typeof ToolsBarcodeGeneratorRoute
  '/tools/base64-encoder': typeof ToolsBase64EncoderRoute
  '/tools/base64-image-encoder': typeof ToolsBase64ImageEncoderRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/credit-card-validator': typeof ToolsCreditCardValidatorRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-gradient-generator': typeof ToolsCssGradientGeneratorRoute
  '/tools/csv-to-json-converter': typeof ToolsCsvToJsonConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/date-calculator': typeof ToolsDateCalculatorRoute
  '/tools/dice-roller': typeof ToolsDiceRollerRoute
  '/tools/discount-calculator': typeof ToolsDiscountCalculatorRoute
  '/tools/duplicate-character-finder': typeof ToolsDuplicateCharacterFinderRoute
  '/tools/flip-coin-simulator': typeof ToolsFlipCoinSimulatorRoute
  '/tools/hash-check-generator': typeof ToolsHashCheckGeneratorRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-encoder-decoder': typeof ToolsHtmlEncoderDecoderRoute
  '/tools/html-minifier': typeof ToolsHtmlMinifierRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/investment-calculator': typeof ToolsInvestmentCalculatorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-csv-converter': typeof ToolsJsonToCsvConverterRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/line-counter': typeof ToolsLineCounterRoute
  '/tools/list-randomizer': typeof ToolsListRandomizerRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/lorem-ipsum-customizer': typeof ToolsLoremIpsumCustomizerRoute
  '/tools/md5-generator': typeof ToolsMd5GeneratorRoute
  '/tools/morse-code-converter': typeof ToolsMorseCodeConverterRoute
  '/tools/number-to-words-converter': typeof ToolsNumberToWordsConverterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/password-strength-tester': typeof ToolsPasswordStrengthTesterRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/random-color-generator': typeof ToolsRandomColorGeneratorRoute
  '/tools/random-id-generator': typeof ToolsRandomIdGeneratorRoute
  '/tools/random-name-generator': typeof ToolsRandomNameGeneratorRoute
  '/tools/random-number-generator': typeof ToolsRandomNumberGeneratorRoute
  '/tools/random-password-generator': typeof ToolsRandomPasswordGeneratorRoute
  '/tools/regex-generator': typeof ToolsRegexGeneratorRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/roman-numeral-converter': typeof ToolsRomanNumeralConverterRoute
  '/tools/slug-checker': typeof ToolsSlugCheckerRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/temperature-converter': typeof ToolsTemperatureConverterRoute
  '/tools/text-diff-checker': typeof ToolsTextDiffCheckerRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/tip-calculator': typeof ToolsTipCalculatorRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encoder': typeof ToolsUrlEncoderRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/tools/vat-calculator': typeof ToolsVatCalculatorRoute
  '/tools/word-counter': typeof ToolsWordCounterRoute
  '/tools/word-frequency-analyzer': typeof ToolsWordFrequencyAnalyzerRoute
  '/tools/xml-formatter': typeof ToolsXmlFormatterRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/compare': typeof CompareIndexRoute
  '/file-types': typeof FileTypesIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/sitemap': typeof SitemapRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/age-calculator': typeof ToolsAgeCalculatorRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/barcode-generator': typeof ToolsBarcodeGeneratorRoute
  '/tools/base64-encoder': typeof ToolsBase64EncoderRoute
  '/tools/base64-image-encoder': typeof ToolsBase64ImageEncoderRoute
  '/tools/binary-converter': typeof ToolsBinaryConverterRoute
  '/tools/bmi-calculator': typeof ToolsBmiCalculatorRoute
  '/tools/case-converter': typeof ToolsCaseConverterRoute
  '/tools/color-converter': typeof ToolsColorConverterRoute
  '/tools/credit-card-validator': typeof ToolsCreditCardValidatorRoute
  '/tools/cron-parser': typeof ToolsCronParserRoute
  '/tools/css-gradient-generator': typeof ToolsCssGradientGeneratorRoute
  '/tools/csv-to-json-converter': typeof ToolsCsvToJsonConverterRoute
  '/tools/currency-converter': typeof ToolsCurrencyConverterRoute
  '/tools/date-calculator': typeof ToolsDateCalculatorRoute
  '/tools/dice-roller': typeof ToolsDiceRollerRoute
  '/tools/discount-calculator': typeof ToolsDiscountCalculatorRoute
  '/tools/duplicate-character-finder': typeof ToolsDuplicateCharacterFinderRoute
  '/tools/flip-coin-simulator': typeof ToolsFlipCoinSimulatorRoute
  '/tools/hash-check-generator': typeof ToolsHashCheckGeneratorRoute
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/hex-converter': typeof ToolsHexConverterRoute
  '/tools/html-encoder-decoder': typeof ToolsHtmlEncoderDecoderRoute
  '/tools/html-minifier': typeof ToolsHtmlMinifierRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/investment-calculator': typeof ToolsInvestmentCalculatorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/json-to-csv-converter': typeof ToolsJsonToCsvConverterRoute
  '/tools/json-validator': typeof ToolsJsonValidatorRoute
  '/tools/jwt-decoder': typeof ToolsJwtDecoderRoute
  '/tools/line-counter': typeof ToolsLineCounterRoute
  '/tools/list-randomizer': typeof ToolsListRandomizerRoute
  '/tools/loan-calculator': typeof ToolsLoanCalculatorRoute
  '/tools/lorem-ipsum': typeof ToolsLoremIpsumRoute
  '/tools/lorem-ipsum-customizer': typeof ToolsLoremIpsumCustomizerRoute
  '/tools/md5-generator': typeof ToolsMd5GeneratorRoute
  '/tools/morse-code-converter': typeof ToolsMorseCodeConverterRoute
  '/tools/number-to-words-converter': typeof ToolsNumberToWordsConverterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/password-strength-tester': typeof ToolsPasswordStrengthTesterRoute
  '/tools/percentage-calculator': typeof ToolsPercentageCalculatorRoute
  '/tools/qr-code-generator': typeof ToolsQrCodeGeneratorRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/random-color-generator': typeof ToolsRandomColorGeneratorRoute
  '/tools/random-id-generator': typeof ToolsRandomIdGeneratorRoute
  '/tools/random-name-generator': typeof ToolsRandomNameGeneratorRoute
  '/tools/random-number-generator': typeof ToolsRandomNumberGeneratorRoute
  '/tools/random-password-generator': typeof ToolsRandomPasswordGeneratorRoute
  '/tools/regex-generator': typeof ToolsRegexGeneratorRoute
  '/tools/regex-tester': typeof ToolsRegexTesterRoute
  '/tools/roman-numeral-converter': typeof ToolsRomanNumeralConverterRoute
  '/tools/slug-checker': typeof ToolsSlugCheckerRoute
  '/tools/slug-generator': typeof ToolsSlugGeneratorRoute
  '/tools/sql-formatter': typeof ToolsSqlFormatterRoute
  '/tools/temperature-converter': typeof ToolsTemperatureConverterRoute
  '/tools/text-diff-checker': typeof ToolsTextDiffCheckerRoute
  '/tools/text-to-speech': typeof ToolsTextToSpeechRoute
  '/tools/time-zone-converter': typeof ToolsTimeZoneConverterRoute
  '/tools/tip-calculator': typeof ToolsTipCalculatorRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/unit-converter': typeof ToolsUnitConverterRoute
  '/tools/url-encoder': typeof ToolsUrlEncoderRoute
  '/tools/url-parser': typeof ToolsUrlParserRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
  '/tools/vat-calculator': typeof ToolsVatCalculatorRoute
  '/tools/word-counter': typeof ToolsWordCounterRoute
  '/tools/word-frequency-analyzer': typeof ToolsWordFrequencyAnalyzerRoute
  '/tools/xml-formatter': typeof ToolsXmlFormatterRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/file-types/': typeof FileTypesIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/sitemap'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/age-calculator'
    | '/tools/background-remover'
    | '/tools/barcode-generator'
    | '/tools/base64-encoder'
    | '/tools/base64-image-encoder'
    | '/tools/binary-converter'
    | '/tools/bmi-calculator'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/credit-card-validator'
    | '/tools/cron-parser'
    | '/tools/css-gradient-generator'
    | '/tools/csv-to-json-converter'
    | '/tools/currency-converter'
    | '/tools/date-calculator'
    | '/tools/dice-roller'
    | '/tools/discount-calculator'
    | '/tools/duplicate-character-finder'
    | '/tools/flip-coin-simulator'
    | '/tools/hash-check-generator'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-encoder-decoder'
    | '/tools/html-minifier'
    | '/tools/image-compressor'
    | '/tools/image-enhancer'
    | '/tools/investment-calculator'
    | '/tools/json-formatter'
    | '/tools/json-to-csv-converter'
    | '/tools/json-validator'
    | '/tools/jwt-decoder'
    | '/tools/line-counter'
    | '/tools/list-randomizer'
    | '/tools/loan-calculator'
    | '/tools/lorem-ipsum'
    | '/tools/lorem-ipsum-customizer'
    | '/tools/md5-generator'
    | '/tools/morse-code-converter'
    | '/tools/number-to-words-converter'
    | '/tools/password-generator'
    | '/tools/password-strength-tester'
    | '/tools/percentage-calculator'
    | '/tools/qr-code-generator'
    | '/tools/qr-generator'
    | '/tools/random-color-generator'
    | '/tools/random-id-generator'
    | '/tools/random-name-generator'
    | '/tools/random-number-generator'
    | '/tools/random-password-generator'
    | '/tools/regex-generator'
    | '/tools/regex-tester'
    | '/tools/roman-numeral-converter'
    | '/tools/slug-checker'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/temperature-converter'
    | '/tools/text-diff-checker'
    | '/tools/text-to-speech'
    | '/tools/time-zone-converter'
    | '/tools/tip-calculator'
    | '/tools/translator'
    | '/tools/unit-converter'
    | '/tools/url-encoder'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
    | '/tools/vat-calculator'
    | '/tools/word-counter'
    | '/tools/word-frequency-analyzer'
    | '/tools/xml-formatter'
    | '/use-cases/$slug'
    | '/blog/'
    | '/collections/'
    | '/compare/'
    | '/file-types/'
    | '/questions/'
    | '/use-cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/sitemap'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/age-calculator'
    | '/tools/background-remover'
    | '/tools/barcode-generator'
    | '/tools/base64-encoder'
    | '/tools/base64-image-encoder'
    | '/tools/binary-converter'
    | '/tools/bmi-calculator'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/credit-card-validator'
    | '/tools/cron-parser'
    | '/tools/css-gradient-generator'
    | '/tools/csv-to-json-converter'
    | '/tools/currency-converter'
    | '/tools/date-calculator'
    | '/tools/dice-roller'
    | '/tools/discount-calculator'
    | '/tools/duplicate-character-finder'
    | '/tools/flip-coin-simulator'
    | '/tools/hash-check-generator'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-encoder-decoder'
    | '/tools/html-minifier'
    | '/tools/image-compressor'
    | '/tools/image-enhancer'
    | '/tools/investment-calculator'
    | '/tools/json-formatter'
    | '/tools/json-to-csv-converter'
    | '/tools/json-validator'
    | '/tools/jwt-decoder'
    | '/tools/line-counter'
    | '/tools/list-randomizer'
    | '/tools/loan-calculator'
    | '/tools/lorem-ipsum'
    | '/tools/lorem-ipsum-customizer'
    | '/tools/md5-generator'
    | '/tools/morse-code-converter'
    | '/tools/number-to-words-converter'
    | '/tools/password-generator'
    | '/tools/password-strength-tester'
    | '/tools/percentage-calculator'
    | '/tools/qr-code-generator'
    | '/tools/qr-generator'
    | '/tools/random-color-generator'
    | '/tools/random-id-generator'
    | '/tools/random-name-generator'
    | '/tools/random-number-generator'
    | '/tools/random-password-generator'
    | '/tools/regex-generator'
    | '/tools/regex-tester'
    | '/tools/roman-numeral-converter'
    | '/tools/slug-checker'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/temperature-converter'
    | '/tools/text-diff-checker'
    | '/tools/text-to-speech'
    | '/tools/time-zone-converter'
    | '/tools/tip-calculator'
    | '/tools/translator'
    | '/tools/unit-converter'
    | '/tools/url-encoder'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
    | '/tools/vat-calculator'
    | '/tools/word-counter'
    | '/tools/word-frequency-analyzer'
    | '/tools/xml-formatter'
    | '/use-cases/$slug'
    | '/blog'
    | '/collections'
    | '/compare'
    | '/file-types'
    | '/questions'
    | '/use-cases'
  id:
    | '__root__'
    | '/'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/sitemap'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/age-calculator'
    | '/tools/background-remover'
    | '/tools/barcode-generator'
    | '/tools/base64-encoder'
    | '/tools/base64-image-encoder'
    | '/tools/binary-converter'
    | '/tools/bmi-calculator'
    | '/tools/case-converter'
    | '/tools/color-converter'
    | '/tools/credit-card-validator'
    | '/tools/cron-parser'
    | '/tools/css-gradient-generator'
    | '/tools/csv-to-json-converter'
    | '/tools/currency-converter'
    | '/tools/date-calculator'
    | '/tools/dice-roller'
    | '/tools/discount-calculator'
    | '/tools/duplicate-character-finder'
    | '/tools/flip-coin-simulator'
    | '/tools/hash-check-generator'
    | '/tools/hash-generator'
    | '/tools/hex-converter'
    | '/tools/html-encoder-decoder'
    | '/tools/html-minifier'
    | '/tools/image-compressor'
    | '/tools/image-enhancer'
    | '/tools/investment-calculator'
    | '/tools/json-formatter'
    | '/tools/json-to-csv-converter'
    | '/tools/json-validator'
    | '/tools/jwt-decoder'
    | '/tools/line-counter'
    | '/tools/list-randomizer'
    | '/tools/loan-calculator'
    | '/tools/lorem-ipsum'
    | '/tools/lorem-ipsum-customizer'
    | '/tools/md5-generator'
    | '/tools/morse-code-converter'
    | '/tools/number-to-words-converter'
    | '/tools/password-generator'
    | '/tools/password-strength-tester'
    | '/tools/percentage-calculator'
    | '/tools/qr-code-generator'
    | '/tools/qr-generator'
    | '/tools/random-color-generator'
    | '/tools/random-id-generator'
    | '/tools/random-name-generator'
    | '/tools/random-number-generator'
    | '/tools/random-password-generator'
    | '/tools/regex-generator'
    | '/tools/regex-tester'
    | '/tools/roman-numeral-converter'
    | '/tools/slug-checker'
    | '/tools/slug-generator'
    | '/tools/sql-formatter'
    | '/tools/temperature-converter'
    | '/tools/text-diff-checker'
    | '/tools/text-to-speech'
    | '/tools/time-zone-converter'
    | '/tools/tip-calculator'
    | '/tools/translator'
    | '/tools/unit-converter'
    | '/tools/url-encoder'
    | '/tools/url-parser'
    | '/tools/uuid-generator'
    | '/tools/vat-calculator'
    | '/tools/word-counter'
    | '/tools/word-frequency-analyzer'
    | '/tools/xml-formatter'
    | '/use-cases/$slug'
    | '/blog/'
    | '/collections/'
    | '/compare/'
    | '/file-types/'
    | '/questions/'
    | '/use-cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioToolsRoute: typeof AudioToolsRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  ImageToolsRoute: typeof ImageToolsRoute
  PdfToolsRoute: typeof PdfToolsRoute
  SitemapRoute: typeof SitemapRoute
  TranslationToolsRoute: typeof TranslationToolsRoute
  VideoToolsRoute: typeof VideoToolsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  FileTypesSlugRoute: typeof FileTypesSlugRoute
  QuestionsSlugRoute: typeof QuestionsSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  ToolsAgeCalculatorRoute: typeof ToolsAgeCalculatorRoute
  ToolsBackgroundRemoverRoute: typeof ToolsBackgroundRemoverRoute
  ToolsBarcodeGeneratorRoute: typeof ToolsBarcodeGeneratorRoute
  ToolsBase64EncoderRoute: typeof ToolsBase64EncoderRoute
  ToolsBase64ImageEncoderRoute: typeof ToolsBase64ImageEncoderRoute
  ToolsBinaryConverterRoute: typeof ToolsBinaryConverterRoute
  ToolsBmiCalculatorRoute: typeof ToolsBmiCalculatorRoute
  ToolsCaseConverterRoute: typeof ToolsCaseConverterRoute
  ToolsColorConverterRoute: typeof ToolsColorConverterRoute
  ToolsCreditCardValidatorRoute: typeof ToolsCreditCardValidatorRoute
  ToolsCronParserRoute: typeof ToolsCronParserRoute
  ToolsCssGradientGeneratorRoute: typeof ToolsCssGradientGeneratorRoute
  ToolsCsvToJsonConverterRoute: typeof ToolsCsvToJsonConverterRoute
  ToolsCurrencyConverterRoute: typeof ToolsCurrencyConverterRoute
  ToolsDateCalculatorRoute: typeof ToolsDateCalculatorRoute
  ToolsDiceRollerRoute: typeof ToolsDiceRollerRoute
  ToolsDiscountCalculatorRoute: typeof ToolsDiscountCalculatorRoute
  ToolsDuplicateCharacterFinderRoute: typeof ToolsDuplicateCharacterFinderRoute
  ToolsFlipCoinSimulatorRoute: typeof ToolsFlipCoinSimulatorRoute
  ToolsHashCheckGeneratorRoute: typeof ToolsHashCheckGeneratorRoute
  ToolsHashGeneratorRoute: typeof ToolsHashGeneratorRoute
  ToolsHexConverterRoute: typeof ToolsHexConverterRoute
  ToolsHtmlEncoderDecoderRoute: typeof ToolsHtmlEncoderDecoderRoute
  ToolsHtmlMinifierRoute: typeof ToolsHtmlMinifierRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsImageEnhancerRoute: typeof ToolsImageEnhancerRoute
  ToolsInvestmentCalculatorRoute: typeof ToolsInvestmentCalculatorRoute
  ToolsJsonFormatterRoute: typeof ToolsJsonFormatterRoute
  ToolsJsonToCsvConverterRoute: typeof ToolsJsonToCsvConverterRoute
  ToolsJsonValidatorRoute: typeof ToolsJsonValidatorRoute
  ToolsJwtDecoderRoute: typeof ToolsJwtDecoderRoute
  ToolsLineCounterRoute: typeof ToolsLineCounterRoute
  ToolsListRandomizerRoute: typeof ToolsListRandomizerRoute
  ToolsLoanCalculatorRoute: typeof ToolsLoanCalculatorRoute
  ToolsLoremIpsumRoute: typeof ToolsLoremIpsumRoute
  ToolsLoremIpsumCustomizerRoute: typeof ToolsLoremIpsumCustomizerRoute
  ToolsMd5GeneratorRoute: typeof ToolsMd5GeneratorRoute
  ToolsMorseCodeConverterRoute: typeof ToolsMorseCodeConverterRoute
  ToolsNumberToWordsConverterRoute: typeof ToolsNumberToWordsConverterRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsPasswordStrengthTesterRoute: typeof ToolsPasswordStrengthTesterRoute
  ToolsPercentageCalculatorRoute: typeof ToolsPercentageCalculatorRoute
  ToolsQrCodeGeneratorRoute: typeof ToolsQrCodeGeneratorRoute
  ToolsQrGeneratorRoute: typeof ToolsQrGeneratorRoute
  ToolsRandomColorGeneratorRoute: typeof ToolsRandomColorGeneratorRoute
  ToolsRandomIdGeneratorRoute: typeof ToolsRandomIdGeneratorRoute
  ToolsRandomNameGeneratorRoute: typeof ToolsRandomNameGeneratorRoute
  ToolsRandomNumberGeneratorRoute: typeof ToolsRandomNumberGeneratorRoute
  ToolsRandomPasswordGeneratorRoute: typeof ToolsRandomPasswordGeneratorRoute
  ToolsRegexGeneratorRoute: typeof ToolsRegexGeneratorRoute
  ToolsRegexTesterRoute: typeof ToolsRegexTesterRoute
  ToolsRomanNumeralConverterRoute: typeof ToolsRomanNumeralConverterRoute
  ToolsSlugCheckerRoute: typeof ToolsSlugCheckerRoute
  ToolsSlugGeneratorRoute: typeof ToolsSlugGeneratorRoute
  ToolsSqlFormatterRoute: typeof ToolsSqlFormatterRoute
  ToolsTemperatureConverterRoute: typeof ToolsTemperatureConverterRoute
  ToolsTextDiffCheckerRoute: typeof ToolsTextDiffCheckerRoute
  ToolsTextToSpeechRoute: typeof ToolsTextToSpeechRoute
  ToolsTimeZoneConverterRoute: typeof ToolsTimeZoneConverterRoute
  ToolsTipCalculatorRoute: typeof ToolsTipCalculatorRoute
  ToolsTranslatorRoute: typeof ToolsTranslatorRoute
  ToolsUnitConverterRoute: typeof ToolsUnitConverterRoute
  ToolsUrlEncoderRoute: typeof ToolsUrlEncoderRoute
  ToolsUrlParserRoute: typeof ToolsUrlParserRoute
  ToolsUuidGeneratorRoute: typeof ToolsUuidGeneratorRoute
  ToolsVatCalculatorRoute: typeof ToolsVatCalculatorRoute
  ToolsWordCounterRoute: typeof ToolsWordCounterRoute
  ToolsWordFrequencyAnalyzerRoute: typeof ToolsWordFrequencyAnalyzerRoute
  ToolsXmlFormatterRoute: typeof ToolsXmlFormatterRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  FileTypesIndexRoute: typeof FileTypesIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-tools': {
      id: '/audio-tools'
      path: '/audio-tools'
      fullPath: '/audio-tools'
      preLoaderRoute: typeof AudioToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools': {
      id: '/image-tools'
      path: '/image-tools'
      fullPath: '/image-tools'
      preLoaderRoute: typeof ImageToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools': {
      id: '/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof PdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translation-tools': {
      id: '/translation-tools'
      path: '/translation-tools'
      fullPath: '/translation-tools'
      preLoaderRoute: typeof TranslationToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-tools': {
      id: '/video-tools'
      path: '/video-tools'
      fullPath: '/video-tools'
      preLoaderRoute: typeof VideoToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-types/': {
      id: '/file-types/'
      path: '/file-types'
      fullPath: '/file-types/'
      preLoaderRoute: typeof FileTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-types/$slug': {
      id: '/file-types/$slug'
      path: '/file-types/$slug'
      fullPath: '/file-types/$slug'
      preLoaderRoute: typeof FileTypesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$slug': {
      id: '/questions/$slug'
      path: '/questions/$slug'
      fullPath: '/questions/$slug'
      preLoaderRoute: typeof QuestionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/age-calculator': {
      id: '/tools/age-calculator'
      path: '/tools/age-calculator'
      fullPath: '/tools/age-calculator'
      preLoaderRoute: typeof ToolsAgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/background-remover': {
      id: '/tools/background-remover'
      path: '/tools/background-remover'
      fullPath: '/tools/background-remover'
      preLoaderRoute: typeof ToolsBackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/barcode-generator': {
      id: '/tools/barcode-generator'
      path: '/tools/barcode-generator'
      fullPath: '/tools/barcode-generator'
      preLoaderRoute: typeof ToolsBarcodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64-encoder': {
      id: '/tools/base64-encoder'
      path: '/tools/base64-encoder'
      fullPath: '/tools/base64-encoder'
      preLoaderRoute: typeof ToolsBase64EncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64-image-encoder': {
      id: '/tools/base64-image-encoder'
      path: '/tools/base64-image-encoder'
      fullPath: '/tools/base64-image-encoder'
      preLoaderRoute: typeof ToolsBase64ImageEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/binary-converter': {
      id: '/tools/binary-converter'
      path: '/tools/binary-converter'
      fullPath: '/tools/binary-converter'
      preLoaderRoute: typeof ToolsBinaryConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bmi-calculator': {
      id: '/tools/bmi-calculator'
      path: '/tools/bmi-calculator'
      fullPath: '/tools/bmi-calculator'
      preLoaderRoute: typeof ToolsBmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/case-converter': {
      id: '/tools/case-converter'
      path: '/tools/case-converter'
      fullPath: '/tools/case-converter'
      preLoaderRoute: typeof ToolsCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-converter': {
      id: '/tools/color-converter'
      path: '/tools/color-converter'
      fullPath: '/tools/color-converter'
      preLoaderRoute: typeof ToolsColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/credit-card-validator': {
      id: '/tools/credit-card-validator'
      path: '/tools/credit-card-validator'
      fullPath: '/tools/credit-card-validator'
      preLoaderRoute: typeof ToolsCreditCardValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cron-parser': {
      id: '/tools/cron-parser'
      path: '/tools/cron-parser'
      fullPath: '/tools/cron-parser'
      preLoaderRoute: typeof ToolsCronParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/css-gradient-generator': {
      id: '/tools/css-gradient-generator'
      path: '/tools/css-gradient-generator'
      fullPath: '/tools/css-gradient-generator'
      preLoaderRoute: typeof ToolsCssGradientGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/csv-to-json-converter': {
      id: '/tools/csv-to-json-converter'
      path: '/tools/csv-to-json-converter'
      fullPath: '/tools/csv-to-json-converter'
      preLoaderRoute: typeof ToolsCsvToJsonConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/currency-converter': {
      id: '/tools/currency-converter'
      path: '/tools/currency-converter'
      fullPath: '/tools/currency-converter'
      preLoaderRoute: typeof ToolsCurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/date-calculator': {
      id: '/tools/date-calculator'
      path: '/tools/date-calculator'
      fullPath: '/tools/date-calculator'
      preLoaderRoute: typeof ToolsDateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/dice-roller': {
      id: '/tools/dice-roller'
      path: '/tools/dice-roller'
      fullPath: '/tools/dice-roller'
      preLoaderRoute: typeof ToolsDiceRollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/discount-calculator': {
      id: '/tools/discount-calculator'
      path: '/tools/discount-calculator'
      fullPath: '/tools/discount-calculator'
      preLoaderRoute: typeof ToolsDiscountCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/duplicate-character-finder': {
      id: '/tools/duplicate-character-finder'
      path: '/tools/duplicate-character-finder'
      fullPath: '/tools/duplicate-character-finder'
      preLoaderRoute: typeof ToolsDuplicateCharacterFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/flip-coin-simulator': {
      id: '/tools/flip-coin-simulator'
      path: '/tools/flip-coin-simulator'
      fullPath: '/tools/flip-coin-simulator'
      preLoaderRoute: typeof ToolsFlipCoinSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash-check-generator': {
      id: '/tools/hash-check-generator'
      path: '/tools/hash-check-generator'
      fullPath: '/tools/hash-check-generator'
      preLoaderRoute: typeof ToolsHashCheckGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash-generator': {
      id: '/tools/hash-generator'
      path: '/tools/hash-generator'
      fullPath: '/tools/hash-generator'
      preLoaderRoute: typeof ToolsHashGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hex-converter': {
      id: '/tools/hex-converter'
      path: '/tools/hex-converter'
      fullPath: '/tools/hex-converter'
      preLoaderRoute: typeof ToolsHexConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/html-encoder-decoder': {
      id: '/tools/html-encoder-decoder'
      path: '/tools/html-encoder-decoder'
      fullPath: '/tools/html-encoder-decoder'
      preLoaderRoute: typeof ToolsHtmlEncoderDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/html-minifier': {
      id: '/tools/html-minifier'
      path: '/tools/html-minifier'
      fullPath: '/tools/html-minifier'
      preLoaderRoute: typeof ToolsHtmlMinifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-enhancer': {
      id: '/tools/image-enhancer'
      path: '/tools/image-enhancer'
      fullPath: '/tools/image-enhancer'
      preLoaderRoute: typeof ToolsImageEnhancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/investment-calculator': {
      id: '/tools/investment-calculator'
      path: '/tools/investment-calculator'
      fullPath: '/tools/investment-calculator'
      preLoaderRoute: typeof ToolsInvestmentCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-formatter': {
      id: '/tools/json-formatter'
      path: '/tools/json-formatter'
      fullPath: '/tools/json-formatter'
      preLoaderRoute: typeof ToolsJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-to-csv-converter': {
      id: '/tools/json-to-csv-converter'
      path: '/tools/json-to-csv-converter'
      fullPath: '/tools/json-to-csv-converter'
      preLoaderRoute: typeof ToolsJsonToCsvConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-validator': {
      id: '/tools/json-validator'
      path: '/tools/json-validator'
      fullPath: '/tools/json-validator'
      preLoaderRoute: typeof ToolsJsonValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jwt-decoder': {
      id: '/tools/jwt-decoder'
      path: '/tools/jwt-decoder'
      fullPath: '/tools/jwt-decoder'
      preLoaderRoute: typeof ToolsJwtDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/line-counter': {
      id: '/tools/line-counter'
      path: '/tools/line-counter'
      fullPath: '/tools/line-counter'
      preLoaderRoute: typeof ToolsLineCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/list-randomizer': {
      id: '/tools/list-randomizer'
      path: '/tools/list-randomizer'
      fullPath: '/tools/list-randomizer'
      preLoaderRoute: typeof ToolsListRandomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/loan-calculator': {
      id: '/tools/loan-calculator'
      path: '/tools/loan-calculator'
      fullPath: '/tools/loan-calculator'
      preLoaderRoute: typeof ToolsLoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/lorem-ipsum': {
      id: '/tools/lorem-ipsum'
      path: '/tools/lorem-ipsum'
      fullPath: '/tools/lorem-ipsum'
      preLoaderRoute: typeof ToolsLoremIpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/lorem-ipsum-customizer': {
      id: '/tools/lorem-ipsum-customizer'
      path: '/tools/lorem-ipsum-customizer'
      fullPath: '/tools/lorem-ipsum-customizer'
      preLoaderRoute: typeof ToolsLoremIpsumCustomizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/md5-generator': {
      id: '/tools/md5-generator'
      path: '/tools/md5-generator'
      fullPath: '/tools/md5-generator'
      preLoaderRoute: typeof ToolsMd5GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/morse-code-converter': {
      id: '/tools/morse-code-converter'
      path: '/tools/morse-code-converter'
      fullPath: '/tools/morse-code-converter'
      preLoaderRoute: typeof ToolsMorseCodeConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/number-to-words-converter': {
      id: '/tools/number-to-words-converter'
      path: '/tools/number-to-words-converter'
      fullPath: '/tools/number-to-words-converter'
      preLoaderRoute: typeof ToolsNumberToWordsConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-strength-tester': {
      id: '/tools/password-strength-tester'
      path: '/tools/password-strength-tester'
      fullPath: '/tools/password-strength-tester'
      preLoaderRoute: typeof ToolsPasswordStrengthTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/percentage-calculator': {
      id: '/tools/percentage-calculator'
      path: '/tools/percentage-calculator'
      fullPath: '/tools/percentage-calculator'
      preLoaderRoute: typeof ToolsPercentageCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-code-generator': {
      id: '/tools/qr-code-generator'
      path: '/tools/qr-code-generator'
      fullPath: '/tools/qr-code-generator'
      preLoaderRoute: typeof ToolsQrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-generator': {
      id: '/tools/qr-generator'
      path: '/tools/qr-generator'
      fullPath: '/tools/qr-generator'
      preLoaderRoute: typeof ToolsQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/random-color-generator': {
      id: '/tools/random-color-generator'
      path: '/tools/random-color-generator'
      fullPath: '/tools/random-color-generator'
      preLoaderRoute: typeof ToolsRandomColorGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/random-id-generator': {
      id: '/tools/random-id-generator'
      path: '/tools/random-id-generator'
      fullPath: '/tools/random-id-generator'
      preLoaderRoute: typeof ToolsRandomIdGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/random-name-generator': {
      id: '/tools/random-name-generator'
      path: '/tools/random-name-generator'
      fullPath: '/tools/random-name-generator'
      preLoaderRoute: typeof ToolsRandomNameGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/random-number-generator': {
      id: '/tools/random-number-generator'
      path: '/tools/random-number-generator'
      fullPath: '/tools/random-number-generator'
      preLoaderRoute: typeof ToolsRandomNumberGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/random-password-generator': {
      id: '/tools/random-password-generator'
      path: '/tools/random-password-generator'
      fullPath: '/tools/random-password-generator'
      preLoaderRoute: typeof ToolsRandomPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/regex-generator': {
      id: '/tools/regex-generator'
      path: '/tools/regex-generator'
      fullPath: '/tools/regex-generator'
      preLoaderRoute: typeof ToolsRegexGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/regex-tester': {
      id: '/tools/regex-tester'
      path: '/tools/regex-tester'
      fullPath: '/tools/regex-tester'
      preLoaderRoute: typeof ToolsRegexTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/roman-numeral-converter': {
      id: '/tools/roman-numeral-converter'
      path: '/tools/roman-numeral-converter'
      fullPath: '/tools/roman-numeral-converter'
      preLoaderRoute: typeof ToolsRomanNumeralConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/slug-checker': {
      id: '/tools/slug-checker'
      path: '/tools/slug-checker'
      fullPath: '/tools/slug-checker'
      preLoaderRoute: typeof ToolsSlugCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/slug-generator': {
      id: '/tools/slug-generator'
      path: '/tools/slug-generator'
      fullPath: '/tools/slug-generator'
      preLoaderRoute: typeof ToolsSlugGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sql-formatter': {
      id: '/tools/sql-formatter'
      path: '/tools/sql-formatter'
      fullPath: '/tools/sql-formatter'
      preLoaderRoute: typeof ToolsSqlFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/temperature-converter': {
      id: '/tools/temperature-converter'
      path: '/tools/temperature-converter'
      fullPath: '/tools/temperature-converter'
      preLoaderRoute: typeof ToolsTemperatureConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-diff-checker': {
      id: '/tools/text-diff-checker'
      path: '/tools/text-diff-checker'
      fullPath: '/tools/text-diff-checker'
      preLoaderRoute: typeof ToolsTextDiffCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-to-speech': {
      id: '/tools/text-to-speech'
      path: '/tools/text-to-speech'
      fullPath: '/tools/text-to-speech'
      preLoaderRoute: typeof ToolsTextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/time-zone-converter': {
      id: '/tools/time-zone-converter'
      path: '/tools/time-zone-converter'
      fullPath: '/tools/time-zone-converter'
      preLoaderRoute: typeof ToolsTimeZoneConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tip-calculator': {
      id: '/tools/tip-calculator'
      path: '/tools/tip-calculator'
      fullPath: '/tools/tip-calculator'
      preLoaderRoute: typeof ToolsTipCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/translator': {
      id: '/tools/translator'
      path: '/tools/translator'
      fullPath: '/tools/translator'
      preLoaderRoute: typeof ToolsTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/unit-converter': {
      id: '/tools/unit-converter'
      path: '/tools/unit-converter'
      fullPath: '/tools/unit-converter'
      preLoaderRoute: typeof ToolsUnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/url-encoder': {
      id: '/tools/url-encoder'
      path: '/tools/url-encoder'
      fullPath: '/tools/url-encoder'
      preLoaderRoute: typeof ToolsUrlEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/url-parser': {
      id: '/tools/url-parser'
      path: '/tools/url-parser'
      fullPath: '/tools/url-parser'
      preLoaderRoute: typeof ToolsUrlParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid-generator': {
      id: '/tools/uuid-generator'
      path: '/tools/uuid-generator'
      fullPath: '/tools/uuid-generator'
      preLoaderRoute: typeof ToolsUuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/vat-calculator': {
      id: '/tools/vat-calculator'
      path: '/tools/vat-calculator'
      fullPath: '/tools/vat-calculator'
      preLoaderRoute: typeof ToolsVatCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/word-counter': {
      id: '/tools/word-counter'
      path: '/tools/word-counter'
      fullPath: '/tools/word-counter'
      preLoaderRoute: typeof ToolsWordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/word-frequency-analyzer': {
      id: '/tools/word-frequency-analyzer'
      path: '/tools/word-frequency-analyzer'
      fullPath: '/tools/word-frequency-analyzer'
      preLoaderRoute: typeof ToolsWordFrequencyAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/xml-formatter': {
      id: '/tools/xml-formatter'
      path: '/tools/xml-formatter'
      fullPath: '/tools/xml-formatter'
      preLoaderRoute: typeof ToolsXmlFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioToolsRoute: AudioToolsRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  ImageToolsRoute: ImageToolsRoute,
  PdfToolsRoute: PdfToolsRoute,
  SitemapRoute: SitemapRoute,
  TranslationToolsRoute: TranslationToolsRoute,
  VideoToolsRoute: VideoToolsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminInboxRoute: AdminInboxRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  FileTypesSlugRoute: FileTypesSlugRoute,
  QuestionsSlugRoute: QuestionsSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  ToolsAgeCalculatorRoute: ToolsAgeCalculatorRoute,
  ToolsBackgroundRemoverRoute: ToolsBackgroundRemoverRoute,
  ToolsBarcodeGeneratorRoute: ToolsBarcodeGeneratorRoute,
  ToolsBase64EncoderRoute: ToolsBase64EncoderRoute,
  ToolsBase64ImageEncoderRoute: ToolsBase64ImageEncoderRoute,
  ToolsBinaryConverterRoute: ToolsBinaryConverterRoute,
  ToolsBmiCalculatorRoute: ToolsBmiCalculatorRoute,
  ToolsCaseConverterRoute: ToolsCaseConverterRoute,
  ToolsColorConverterRoute: ToolsColorConverterRoute,
  ToolsCreditCardValidatorRoute: ToolsCreditCardValidatorRoute,
  ToolsCronParserRoute: ToolsCronParserRoute,
  ToolsCssGradientGeneratorRoute: ToolsCssGradientGeneratorRoute,
  ToolsCsvToJsonConverterRoute: ToolsCsvToJsonConverterRoute,
  ToolsCurrencyConverterRoute: ToolsCurrencyConverterRoute,
  ToolsDateCalculatorRoute: ToolsDateCalculatorRoute,
  ToolsDiceRollerRoute: ToolsDiceRollerRoute,
  ToolsDiscountCalculatorRoute: ToolsDiscountCalculatorRoute,
  ToolsDuplicateCharacterFinderRoute: ToolsDuplicateCharacterFinderRoute,
  ToolsFlipCoinSimulatorRoute: ToolsFlipCoinSimulatorRoute,
  ToolsHashCheckGeneratorRoute: ToolsHashCheckGeneratorRoute,
  ToolsHashGeneratorRoute: ToolsHashGeneratorRoute,
  ToolsHexConverterRoute: ToolsHexConverterRoute,
  ToolsHtmlEncoderDecoderRoute: ToolsHtmlEncoderDecoderRoute,
  ToolsHtmlMinifierRoute: ToolsHtmlMinifierRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsImageEnhancerRoute: ToolsImageEnhancerRoute,
  ToolsInvestmentCalculatorRoute: ToolsInvestmentCalculatorRoute,
  ToolsJsonFormatterRoute: ToolsJsonFormatterRoute,
  ToolsJsonToCsvConverterRoute: ToolsJsonToCsvConverterRoute,
  ToolsJsonValidatorRoute: ToolsJsonValidatorRoute,
  ToolsJwtDecoderRoute: ToolsJwtDecoderRoute,
  ToolsLineCounterRoute: ToolsLineCounterRoute,
  ToolsListRandomizerRoute: ToolsListRandomizerRoute,
  ToolsLoanCalculatorRoute: ToolsLoanCalculatorRoute,
  ToolsLoremIpsumRoute: ToolsLoremIpsumRoute,
  ToolsLoremIpsumCustomizerRoute: ToolsLoremIpsumCustomizerRoute,
  ToolsMd5GeneratorRoute: ToolsMd5GeneratorRoute,
  ToolsMorseCodeConverterRoute: ToolsMorseCodeConverterRoute,
  ToolsNumberToWordsConverterRoute: ToolsNumberToWordsConverterRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsPasswordStrengthTesterRoute: ToolsPasswordStrengthTesterRoute,
  ToolsPercentageCalculatorRoute: ToolsPercentageCalculatorRoute,
  ToolsQrCodeGeneratorRoute: ToolsQrCodeGeneratorRoute,
  ToolsQrGeneratorRoute: ToolsQrGeneratorRoute,
  ToolsRandomColorGeneratorRoute: ToolsRandomColorGeneratorRoute,
  ToolsRandomIdGeneratorRoute: ToolsRandomIdGeneratorRoute,
  ToolsRandomNameGeneratorRoute: ToolsRandomNameGeneratorRoute,
  ToolsRandomNumberGeneratorRoute: ToolsRandomNumberGeneratorRoute,
  ToolsRandomPasswordGeneratorRoute: ToolsRandomPasswordGeneratorRoute,
  ToolsRegexGeneratorRoute: ToolsRegexGeneratorRoute,
  ToolsRegexTesterRoute: ToolsRegexTesterRoute,
  ToolsRomanNumeralConverterRoute: ToolsRomanNumeralConverterRoute,
  ToolsSlugCheckerRoute: ToolsSlugCheckerRoute,
  ToolsSlugGeneratorRoute: ToolsSlugGeneratorRoute,
  ToolsSqlFormatterRoute: ToolsSqlFormatterRoute,
  ToolsTemperatureConverterRoute: ToolsTemperatureConverterRoute,
  ToolsTextDiffCheckerRoute: ToolsTextDiffCheckerRoute,
  ToolsTextToSpeechRoute: ToolsTextToSpeechRoute,
  ToolsTimeZoneConverterRoute: ToolsTimeZoneConverterRoute,
  ToolsTipCalculatorRoute: ToolsTipCalculatorRoute,
  ToolsTranslatorRoute: ToolsTranslatorRoute,
  ToolsUnitConverterRoute: ToolsUnitConverterRoute,
  ToolsUrlEncoderRoute: ToolsUrlEncoderRoute,
  ToolsUrlParserRoute: ToolsUrlParserRoute,
  ToolsUuidGeneratorRoute: ToolsUuidGeneratorRoute,
  ToolsVatCalculatorRoute: ToolsVatCalculatorRoute,
  ToolsWordCounterRoute: ToolsWordCounterRoute,
  ToolsWordFrequencyAnalyzerRoute: ToolsWordFrequencyAnalyzerRoute,
  ToolsXmlFormatterRoute: ToolsXmlFormatterRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  FileTypesIndexRoute: FileTypesIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
