/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AudioToolsRouteImport } from './routes/audio-tools'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ImageToolsRouteImport } from './routes/image-tools'
import { Route as PdfToolsRouteImport } from './routes/pdf-tools'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TranslationToolsRouteImport } from './routes/translation-tools'
import { Route as VideoToolsRouteImport } from './routes/video-tools'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as FileTypesIndexRouteImport } from './routes/file-types/index'
import { Route as FileTypesSlugRouteImport } from './routes/file-types/$slug'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsSlugRouteImport } from './routes/questions/$slug'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsSlugRouteImport } from './routes/tools/$slug'
import { Route as ToolsAiWriterRouteImport } from './routes/tools/ai-writer'
import { Route as ToolsArticleGeneratorRouteImport } from './routes/tools/article-generator'
import { Route as ToolsBackgroundChangerRouteImport } from './routes/tools/background-changer'
import { Route as ToolsBackgroundRemoverRouteImport } from './routes/tools/background-remover'
import { Route as ToolsBlogGeneratorRouteImport } from './routes/tools/blog-generator'
import { Route as ToolsBlurImageRouteImport } from './routes/tools/blur-image'
import { Route as ToolsColorPaletteGeneratorRouteImport } from './routes/tools/color-palette-generator'
import { Route as ToolsColorPickerRouteImport } from './routes/tools/color-picker'
import { Route as ToolsCropImageRouteImport } from './routes/tools/crop-image'
import { Route as ToolsDocumentTranslatorRouteImport } from './routes/tools/document-translator'
import { Route as ToolsDocxTranslatorRouteImport } from './routes/tools/docx-translator'
import { Route as ToolsExcelToPdfRouteImport } from './routes/tools/excel-to-pdf'
import { Route as ToolsFaceBlurRouteImport } from './routes/tools/face-blur'
import { Route as ToolsGrammarCheckerRouteImport } from './routes/tools/grammar-checker'
import { Route as ToolsImageCompressorRouteImport } from './routes/tools/image-compressor'
import { Route as ToolsImageConverterRouteImport } from './routes/tools/image-converter'
import { Route as ToolsImageEditorRouteImport } from './routes/tools/image-editor'
import { Route as ToolsImageEnhancerRouteImport } from './routes/tools/image-enhancer'
import { Route as ToolsImageGeneratorRouteImport } from './routes/tools/image-generator'
import { Route as ToolsImageOcrRouteImport } from './routes/tools/image-ocr'
import { Route as ToolsImageResizerRouteImport } from './routes/tools/image-resizer'
import { Route as ToolsImageToPdfRouteImport } from './routes/tools/image-to-pdf'
import { Route as ToolsImageTranslatorRouteImport } from './routes/tools/image-translator'
import { Route as ToolsImageUpscalerRouteImport } from './routes/tools/image-upscaler'
import { Route as ToolsJpgToPdfRouteImport } from './routes/tools/jpg-to-pdf'
import { Route as ToolsLanguageDetectionRouteImport } from './routes/tools/language-detection'
import { Route as ToolsLargeTextTranslatorRouteImport } from './routes/tools/large-text-translator'
import { Route as ToolsOcrTranslatorRouteImport } from './routes/tools/ocr-translator'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools/password-generator'
import { Route as ToolsPdfCompressRouteImport } from './routes/tools/pdf-compress'
import { Route as ToolsPdfEditRouteImport } from './routes/tools/pdf-edit'
import { Route as ToolsPdfExtractPagesRouteImport } from './routes/tools/pdf-extract-pages'
import { Route as ToolsPdfMergeRouteImport } from './routes/tools/pdf-merge'
import { Route as ToolsPdfOcrRouteImport } from './routes/tools/pdf-ocr'
import { Route as ToolsPdfProtectRouteImport } from './routes/tools/pdf-protect'
import { Route as ToolsPdfRotateRouteImport } from './routes/tools/pdf-rotate'
import { Route as ToolsPdfSignRouteImport } from './routes/tools/pdf-sign'
import { Route as ToolsPdfSplitRouteImport } from './routes/tools/pdf-split'
import { Route as ToolsPdfToJpgRouteImport } from './routes/tools/pdf-to-jpg'
import { Route as ToolsPdfToWordRouteImport } from './routes/tools/pdf-to-word'
import { Route as ToolsPdfTranslatorRouteImport } from './routes/tools/pdf-translator'
import { Route as ToolsPdfUnlockRouteImport } from './routes/tools/pdf-unlock'
import { Route as ToolsPdfWatermarkRouteImport } from './routes/tools/pdf-watermark'
import { Route as ToolsPowerpointToPdfRouteImport } from './routes/tools/powerpoint-to-pdf'
import { Route as ToolsQrGeneratorRouteImport } from './routes/tools/qr-generator'
import { Route as ToolsRewriteTextRouteImport } from './routes/tools/rewrite-text'
import { Route as ToolsRotateImageRouteImport } from './routes/tools/rotate-image'
import { Route as ToolsScreenshotEditorRouteImport } from './routes/tools/screenshot-editor'
import { Route as ToolsSharpenImageRouteImport } from './routes/tools/sharpen-image'
import { Route as ToolsSubtitleTranslatorRouteImport } from './routes/tools/subtitle-translator'
import { Route as ToolsSummarizerRouteImport } from './routes/tools/summarizer'
import { Route as ToolsTranslatorRouteImport } from './routes/tools/translator'
import { Route as ToolsVoiceTranslatorRouteImport } from './routes/tools/voice-translator'
import { Route as ToolsWatermarkRemoverRouteImport } from './routes/tools/watermark-remover'
import { Route as ToolsWebsiteTranslatorRouteImport } from './routes/tools/website-translator'
import { Route as ToolsWordToPdfRouteImport } from './routes/tools/word-to-pdf'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases/$slug'
import { Route as KnowledgeArticleSlugRouteImport } from './routes/knowledge/article/$slug'
import { Route as KnowledgeBestSlugRouteImport } from './routes/knowledge/best/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioToolsRoute = AudioToolsRouteImport.update({
  id: '/audio-tools',
  path: '/audio-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsRoute = ImageToolsRouteImport.update({
  id: '/image-tools',
  path: '/image-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsRoute = PdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslationToolsRoute = TranslationToolsRouteImport.update({
  id: '/translation-tools',
  path: '/translation-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToolsRoute = VideoToolsRouteImport.update({
  id: '/video-tools',
  path: '/video-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FileTypesIndexRoute = FileTypesIndexRouteImport.update({
  id: '/file-types/',
  path: '/file-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileTypesSlugRoute = FileTypesSlugRouteImport.update({
  id: '/file-types/$slug',
  path: '/file-types/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsSlugRoute = QuestionsSlugRouteImport.update({
  id: '/questions/$slug',
  path: '/questions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAiWriterRoute = ToolsAiWriterRouteImport.update({
  id: '/tools/ai-writer',
  path: '/tools/ai-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsArticleGeneratorRoute = ToolsArticleGeneratorRouteImport.update({
  id: '/tools/article-generator',
  path: '/tools/article-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBackgroundChangerRoute = ToolsBackgroundChangerRouteImport.update({
  id: '/tools/background-changer',
  path: '/tools/background-changer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBackgroundRemoverRoute = ToolsBackgroundRemoverRouteImport.update({
  id: '/tools/background-remover',
  path: '/tools/background-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBlogGeneratorRoute = ToolsBlogGeneratorRouteImport.update({
  id: '/tools/blog-generator',
  path: '/tools/blog-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBlurImageRoute = ToolsBlurImageRouteImport.update({
  id: '/tools/blur-image',
  path: '/tools/blur-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsColorPaletteGeneratorRoute =
  ToolsColorPaletteGeneratorRouteImport.update({
    id: '/tools/color-palette-generator',
    path: '/tools/color-palette-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsColorPickerRoute = ToolsColorPickerRouteImport.update({
  id: '/tools/color-picker',
  path: '/tools/color-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCropImageRoute = ToolsCropImageRouteImport.update({
  id: '/tools/crop-image',
  path: '/tools/crop-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDocumentTranslatorRoute = ToolsDocumentTranslatorRouteImport.update({
  id: '/tools/document-translator',
  path: '/tools/document-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDocxTranslatorRoute = ToolsDocxTranslatorRouteImport.update({
  id: '/tools/docx-translator',
  path: '/tools/docx-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsExcelToPdfRoute = ToolsExcelToPdfRouteImport.update({
  id: '/tools/excel-to-pdf',
  path: '/tools/excel-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFaceBlurRoute = ToolsFaceBlurRouteImport.update({
  id: '/tools/face-blur',
  path: '/tools/face-blur',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGrammarCheckerRoute = ToolsGrammarCheckerRouteImport.update({
  id: '/tools/grammar-checker',
  path: '/tools/grammar-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageCompressorRoute = ToolsImageCompressorRouteImport.update({
  id: '/tools/image-compressor',
  path: '/tools/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageConverterRoute = ToolsImageConverterRouteImport.update({
  id: '/tools/image-converter',
  path: '/tools/image-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageEditorRoute = ToolsImageEditorRouteImport.update({
  id: '/tools/image-editor',
  path: '/tools/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageEnhancerRoute = ToolsImageEnhancerRouteImport.update({
  id: '/tools/image-enhancer',
  path: '/tools/image-enhancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageGeneratorRoute = ToolsImageGeneratorRouteImport.update({
  id: '/tools/image-generator',
  path: '/tools/image-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageOcrRoute = ToolsImageOcrRouteImport.update({
  id: '/tools/image-ocr',
  path: '/tools/image-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageResizerRoute = ToolsImageResizerRouteImport.update({
  id: '/tools/image-resizer',
  path: '/tools/image-resizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToPdfRoute = ToolsImageToPdfRouteImport.update({
  id: '/tools/image-to-pdf',
  path: '/tools/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageTranslatorRoute = ToolsImageTranslatorRouteImport.update({
  id: '/tools/image-translator',
  path: '/tools/image-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageUpscalerRoute = ToolsImageUpscalerRouteImport.update({
  id: '/tools/image-upscaler',
  path: '/tools/image-upscaler',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJpgToPdfRoute = ToolsJpgToPdfRouteImport.update({
  id: '/tools/jpg-to-pdf',
  path: '/tools/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLanguageDetectionRoute = ToolsLanguageDetectionRouteImport.update({
  id: '/tools/language-detection',
  path: '/tools/language-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLargeTextTranslatorRoute =
  ToolsLargeTextTranslatorRouteImport.update({
    id: '/tools/large-text-translator',
    path: '/tools/large-text-translator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsOcrTranslatorRoute = ToolsOcrTranslatorRouteImport.update({
  id: '/tools/ocr-translator',
  path: '/tools/ocr-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/tools/password-generator',
  path: '/tools/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfCompressRoute = ToolsPdfCompressRouteImport.update({
  id: '/tools/pdf-compress',
  path: '/tools/pdf-compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfEditRoute = ToolsPdfEditRouteImport.update({
  id: '/tools/pdf-edit',
  path: '/tools/pdf-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfExtractPagesRoute = ToolsPdfExtractPagesRouteImport.update({
  id: '/tools/pdf-extract-pages',
  path: '/tools/pdf-extract-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfMergeRoute = ToolsPdfMergeRouteImport.update({
  id: '/tools/pdf-merge',
  path: '/tools/pdf-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfOcrRoute = ToolsPdfOcrRouteImport.update({
  id: '/tools/pdf-ocr',
  path: '/tools/pdf-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfProtectRoute = ToolsPdfProtectRouteImport.update({
  id: '/tools/pdf-protect',
  path: '/tools/pdf-protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfRotateRoute = ToolsPdfRotateRouteImport.update({
  id: '/tools/pdf-rotate',
  path: '/tools/pdf-rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfSignRoute = ToolsPdfSignRouteImport.update({
  id: '/tools/pdf-sign',
  path: '/tools/pdf-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfSplitRoute = ToolsPdfSplitRouteImport.update({
  id: '/tools/pdf-split',
  path: '/tools/pdf-split',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToJpgRoute = ToolsPdfToJpgRouteImport.update({
  id: '/tools/pdf-to-jpg',
  path: '/tools/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToWordRoute = ToolsPdfToWordRouteImport.update({
  id: '/tools/pdf-to-word',
  path: '/tools/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfTranslatorRoute = ToolsPdfTranslatorRouteImport.update({
  id: '/tools/pdf-translator',
  path: '/tools/pdf-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfUnlockRoute = ToolsPdfUnlockRouteImport.update({
  id: '/tools/pdf-unlock',
  path: '/tools/pdf-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfWatermarkRoute = ToolsPdfWatermarkRouteImport.update({
  id: '/tools/pdf-watermark',
  path: '/tools/pdf-watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPowerpointToPdfRoute = ToolsPowerpointToPdfRouteImport.update({
  id: '/tools/powerpoint-to-pdf',
  path: '/tools/powerpoint-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrGeneratorRoute = ToolsQrGeneratorRouteImport.update({
  id: '/tools/qr-generator',
  path: '/tools/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRewriteTextRoute = ToolsRewriteTextRouteImport.update({
  id: '/tools/rewrite-text',
  path: '/tools/rewrite-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRotateImageRoute = ToolsRotateImageRouteImport.update({
  id: '/tools/rotate-image',
  path: '/tools/rotate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsScreenshotEditorRoute = ToolsScreenshotEditorRouteImport.update({
  id: '/tools/screenshot-editor',
  path: '/tools/screenshot-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSharpenImageRoute = ToolsSharpenImageRouteImport.update({
  id: '/tools/sharpen-image',
  path: '/tools/sharpen-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSubtitleTranslatorRoute = ToolsSubtitleTranslatorRouteImport.update({
  id: '/tools/subtitle-translator',
  path: '/tools/subtitle-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSummarizerRoute = ToolsSummarizerRouteImport.update({
  id: '/tools/summarizer',
  path: '/tools/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTranslatorRoute = ToolsTranslatorRouteImport.update({
  id: '/tools/translator',
  path: '/tools/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVoiceTranslatorRoute = ToolsVoiceTranslatorRouteImport.update({
  id: '/tools/voice-translator',
  path: '/tools/voice-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWatermarkRemoverRoute = ToolsWatermarkRemoverRouteImport.update({
  id: '/tools/watermark-remover',
  path: '/tools/watermark-remover',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWebsiteTranslatorRoute = ToolsWebsiteTranslatorRouteImport.update({
  id: '/tools/website-translator',
  path: '/tools/website-translator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWordToPdfRoute = ToolsWordToPdfRouteImport.update({
  id: '/tools/word-to-pdf',
  path: '/tools/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/use-cases/',
  path: '/use-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeArticleSlugRoute = KnowledgeArticleSlugRouteImport.update({
  id: '/knowledge/article/$slug',
  path: '/knowledge/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBestSlugRoute = KnowledgeBestSlugRouteImport.update({
  id: '/knowledge/best/$slug',
  path: '/knowledge/best/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-writer': typeof ToolsAiWriterRoute
  '/tools/article-generator': typeof ToolsArticleGeneratorRoute
  '/tools/background-changer': typeof ToolsBackgroundChangerRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/blog-generator': typeof ToolsBlogGeneratorRoute
  '/tools/blur-image': typeof ToolsBlurImageRoute
  '/tools/color-palette-generator': typeof ToolsColorPaletteGeneratorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crop-image': typeof ToolsCropImageRoute
  '/tools/document-translator': typeof ToolsDocumentTranslatorRoute
  '/tools/docx-translator': typeof ToolsDocxTranslatorRoute
  '/tools/excel-to-pdf': typeof ToolsExcelToPdfRoute
  '/tools/face-blur': typeof ToolsFaceBlurRoute
  '/tools/grammar-checker': typeof ToolsGrammarCheckerRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-editor': typeof ToolsImageEditorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/image-generator': typeof ToolsImageGeneratorRoute
  '/tools/image-ocr': typeof ToolsImageOcrRoute
  '/tools/image-resizer': typeof ToolsImageResizerRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/image-translator': typeof ToolsImageTranslatorRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/language-detection': typeof ToolsLanguageDetectionRoute
  '/tools/large-text-translator': typeof ToolsLargeTextTranslatorRoute
  '/tools/ocr-translator': typeof ToolsOcrTranslatorRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-compress': typeof ToolsPdfCompressRoute
  '/tools/pdf-edit': typeof ToolsPdfEditRoute
  '/tools/pdf-extract-pages': typeof ToolsPdfExtractPagesRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/pdf-ocr': typeof ToolsPdfOcrRoute
  '/tools/pdf-protect': typeof ToolsPdfProtectRoute
  '/tools/pdf-rotate': typeof ToolsPdfRotateRoute
  '/tools/pdf-sign': typeof ToolsPdfSignRoute
  '/tools/pdf-split': typeof ToolsPdfSplitRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/pdf-translator': typeof ToolsPdfTranslatorRoute
  '/tools/pdf-unlock': typeof ToolsPdfUnlockRoute
  '/tools/pdf-watermark': typeof ToolsPdfWatermarkRoute
  '/tools/powerpoint-to-pdf': typeof ToolsPowerpointToPdfRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/rewrite-text': typeof ToolsRewriteTextRoute
  '/tools/rotate-image': typeof ToolsRotateImageRoute
  '/tools/screenshot-editor': typeof ToolsScreenshotEditorRoute
  '/tools/sharpen-image': typeof ToolsSharpenImageRoute
  '/tools/subtitle-translator': typeof ToolsSubtitleTranslatorRoute
  '/tools/summarizer': typeof ToolsSummarizerRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/voice-translator': typeof ToolsVoiceTranslatorRoute
  '/tools/watermark-remover': typeof ToolsWatermarkRemoverRoute
  '/tools/website-translator': typeof ToolsWebsiteTranslatorRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/file-types/': typeof FileTypesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/knowledge/article/$slug': typeof KnowledgeArticleSlugRoute
  '/knowledge/best/$slug': typeof KnowledgeBestSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-writer': typeof ToolsAiWriterRoute
  '/tools/article-generator': typeof ToolsArticleGeneratorRoute
  '/tools/background-changer': typeof ToolsBackgroundChangerRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/blog-generator': typeof ToolsBlogGeneratorRoute
  '/tools/blur-image': typeof ToolsBlurImageRoute
  '/tools/color-palette-generator': typeof ToolsColorPaletteGeneratorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crop-image': typeof ToolsCropImageRoute
  '/tools/document-translator': typeof ToolsDocumentTranslatorRoute
  '/tools/docx-translator': typeof ToolsDocxTranslatorRoute
  '/tools/excel-to-pdf': typeof ToolsExcelToPdfRoute
  '/tools/face-blur': typeof ToolsFaceBlurRoute
  '/tools/grammar-checker': typeof ToolsGrammarCheckerRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-editor': typeof ToolsImageEditorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/image-generator': typeof ToolsImageGeneratorRoute
  '/tools/image-ocr': typeof ToolsImageOcrRoute
  '/tools/image-resizer': typeof ToolsImageResizerRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/image-translator': typeof ToolsImageTranslatorRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/language-detection': typeof ToolsLanguageDetectionRoute
  '/tools/large-text-translator': typeof ToolsLargeTextTranslatorRoute
  '/tools/ocr-translator': typeof ToolsOcrTranslatorRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-compress': typeof ToolsPdfCompressRoute
  '/tools/pdf-edit': typeof ToolsPdfEditRoute
  '/tools/pdf-extract-pages': typeof ToolsPdfExtractPagesRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/pdf-ocr': typeof ToolsPdfOcrRoute
  '/tools/pdf-protect': typeof ToolsPdfProtectRoute
  '/tools/pdf-rotate': typeof ToolsPdfRotateRoute
  '/tools/pdf-sign': typeof ToolsPdfSignRoute
  '/tools/pdf-split': typeof ToolsPdfSplitRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/pdf-translator': typeof ToolsPdfTranslatorRoute
  '/tools/pdf-unlock': typeof ToolsPdfUnlockRoute
  '/tools/pdf-watermark': typeof ToolsPdfWatermarkRoute
  '/tools/powerpoint-to-pdf': typeof ToolsPowerpointToPdfRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/rewrite-text': typeof ToolsRewriteTextRoute
  '/tools/rotate-image': typeof ToolsRotateImageRoute
  '/tools/screenshot-editor': typeof ToolsScreenshotEditorRoute
  '/tools/sharpen-image': typeof ToolsSharpenImageRoute
  '/tools/subtitle-translator': typeof ToolsSubtitleTranslatorRoute
  '/tools/summarizer': typeof ToolsSummarizerRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/voice-translator': typeof ToolsVoiceTranslatorRoute
  '/tools/watermark-remover': typeof ToolsWatermarkRemoverRoute
  '/tools/website-translator': typeof ToolsWebsiteTranslatorRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/compare': typeof CompareIndexRoute
  '/file-types': typeof FileTypesIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/questions': typeof QuestionsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/knowledge/article/$slug': typeof KnowledgeArticleSlugRoute
  '/knowledge/best/$slug': typeof KnowledgeBestSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tools': typeof AiToolsRoute
  '/audio-tools': typeof AudioToolsRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/image-tools': typeof ImageToolsRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/translation-tools': typeof TranslationToolsRoute
  '/video-tools': typeof VideoToolsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/file-types/$slug': typeof FileTypesSlugRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/ai-writer': typeof ToolsAiWriterRoute
  '/tools/article-generator': typeof ToolsArticleGeneratorRoute
  '/tools/background-changer': typeof ToolsBackgroundChangerRoute
  '/tools/background-remover': typeof ToolsBackgroundRemoverRoute
  '/tools/blog-generator': typeof ToolsBlogGeneratorRoute
  '/tools/blur-image': typeof ToolsBlurImageRoute
  '/tools/color-palette-generator': typeof ToolsColorPaletteGeneratorRoute
  '/tools/color-picker': typeof ToolsColorPickerRoute
  '/tools/crop-image': typeof ToolsCropImageRoute
  '/tools/document-translator': typeof ToolsDocumentTranslatorRoute
  '/tools/docx-translator': typeof ToolsDocxTranslatorRoute
  '/tools/excel-to-pdf': typeof ToolsExcelToPdfRoute
  '/tools/face-blur': typeof ToolsFaceBlurRoute
  '/tools/grammar-checker': typeof ToolsGrammarCheckerRoute
  '/tools/image-compressor': typeof ToolsImageCompressorRoute
  '/tools/image-converter': typeof ToolsImageConverterRoute
  '/tools/image-editor': typeof ToolsImageEditorRoute
  '/tools/image-enhancer': typeof ToolsImageEnhancerRoute
  '/tools/image-generator': typeof ToolsImageGeneratorRoute
  '/tools/image-ocr': typeof ToolsImageOcrRoute
  '/tools/image-resizer': typeof ToolsImageResizerRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/image-translator': typeof ToolsImageTranslatorRoute
  '/tools/image-upscaler': typeof ToolsImageUpscalerRoute
  '/tools/jpg-to-pdf': typeof ToolsJpgToPdfRoute
  '/tools/language-detection': typeof ToolsLanguageDetectionRoute
  '/tools/large-text-translator': typeof ToolsLargeTextTranslatorRoute
  '/tools/ocr-translator': typeof ToolsOcrTranslatorRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/pdf-compress': typeof ToolsPdfCompressRoute
  '/tools/pdf-edit': typeof ToolsPdfEditRoute
  '/tools/pdf-extract-pages': typeof ToolsPdfExtractPagesRoute
  '/tools/pdf-merge': typeof ToolsPdfMergeRoute
  '/tools/pdf-ocr': typeof ToolsPdfOcrRoute
  '/tools/pdf-protect': typeof ToolsPdfProtectRoute
  '/tools/pdf-rotate': typeof ToolsPdfRotateRoute
  '/tools/pdf-sign': typeof ToolsPdfSignRoute
  '/tools/pdf-split': typeof ToolsPdfSplitRoute
  '/tools/pdf-to-jpg': typeof ToolsPdfToJpgRoute
  '/tools/pdf-to-word': typeof ToolsPdfToWordRoute
  '/tools/pdf-translator': typeof ToolsPdfTranslatorRoute
  '/tools/pdf-unlock': typeof ToolsPdfUnlockRoute
  '/tools/pdf-watermark': typeof ToolsPdfWatermarkRoute
  '/tools/powerpoint-to-pdf': typeof ToolsPowerpointToPdfRoute
  '/tools/qr-generator': typeof ToolsQrGeneratorRoute
  '/tools/rewrite-text': typeof ToolsRewriteTextRoute
  '/tools/rotate-image': typeof ToolsRotateImageRoute
  '/tools/screenshot-editor': typeof ToolsScreenshotEditorRoute
  '/tools/sharpen-image': typeof ToolsSharpenImageRoute
  '/tools/subtitle-translator': typeof ToolsSubtitleTranslatorRoute
  '/tools/summarizer': typeof ToolsSummarizerRoute
  '/tools/translator': typeof ToolsTranslatorRoute
  '/tools/voice-translator': typeof ToolsVoiceTranslatorRoute
  '/tools/watermark-remover': typeof ToolsWatermarkRemoverRoute
  '/tools/website-translator': typeof ToolsWebsiteTranslatorRoute
  '/tools/word-to-pdf': typeof ToolsWordToPdfRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/file-types/': typeof FileTypesIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/questions/': typeof QuestionsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/knowledge/article/$slug': typeof KnowledgeArticleSlugRoute
  '/knowledge/best/$slug': typeof KnowledgeBestSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/$slug'
    | '/tools/ai-writer'
    | '/tools/article-generator'
    | '/tools/background-changer'
    | '/tools/background-remover'
    | '/tools/blog-generator'
    | '/tools/blur-image'
    | '/tools/color-palette-generator'
    | '/tools/color-picker'
    | '/tools/crop-image'
    | '/tools/document-translator'
    | '/tools/docx-translator'
    | '/tools/excel-to-pdf'
    | '/tools/face-blur'
    | '/tools/grammar-checker'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-editor'
    | '/tools/image-enhancer'
    | '/tools/image-generator'
    | '/tools/image-ocr'
    | '/tools/image-resizer'
    | '/tools/image-to-pdf'
    | '/tools/image-translator'
    | '/tools/image-upscaler'
    | '/tools/jpg-to-pdf'
    | '/tools/language-detection'
    | '/tools/large-text-translator'
    | '/tools/ocr-translator'
    | '/tools/password-generator'
    | '/tools/pdf-compress'
    | '/tools/pdf-edit'
    | '/tools/pdf-extract-pages'
    | '/tools/pdf-merge'
    | '/tools/pdf-ocr'
    | '/tools/pdf-protect'
    | '/tools/pdf-rotate'
    | '/tools/pdf-sign'
    | '/tools/pdf-split'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/pdf-translator'
    | '/tools/pdf-unlock'
    | '/tools/pdf-watermark'
    | '/tools/powerpoint-to-pdf'
    | '/tools/qr-generator'
    | '/tools/rewrite-text'
    | '/tools/rotate-image'
    | '/tools/screenshot-editor'
    | '/tools/sharpen-image'
    | '/tools/subtitle-translator'
    | '/tools/summarizer'
    | '/tools/translator'
    | '/tools/voice-translator'
    | '/tools/watermark-remover'
    | '/tools/website-translator'
    | '/tools/word-to-pdf'
    | '/use-cases/$slug'
    | '/blog/'
    | '/collections/'
    | '/compare/'
    | '/file-types/'
    | '/knowledge/'
    | '/questions/'
    | '/tools/'
    | '/use-cases/'
    | '/knowledge/article/$slug'
    | '/knowledge/best/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-tools'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/$slug'
    | '/tools/ai-writer'
    | '/tools/article-generator'
    | '/tools/background-changer'
    | '/tools/background-remover'
    | '/tools/blog-generator'
    | '/tools/blur-image'
    | '/tools/color-palette-generator'
    | '/tools/color-picker'
    | '/tools/crop-image'
    | '/tools/document-translator'
    | '/tools/docx-translator'
    | '/tools/excel-to-pdf'
    | '/tools/face-blur'
    | '/tools/grammar-checker'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-editor'
    | '/tools/image-enhancer'
    | '/tools/image-generator'
    | '/tools/image-ocr'
    | '/tools/image-resizer'
    | '/tools/image-to-pdf'
    | '/tools/image-translator'
    | '/tools/image-upscaler'
    | '/tools/jpg-to-pdf'
    | '/tools/language-detection'
    | '/tools/large-text-translator'
    | '/tools/ocr-translator'
    | '/tools/password-generator'
    | '/tools/pdf-compress'
    | '/tools/pdf-edit'
    | '/tools/pdf-extract-pages'
    | '/tools/pdf-merge'
    | '/tools/pdf-ocr'
    | '/tools/pdf-protect'
    | '/tools/pdf-rotate'
    | '/tools/pdf-sign'
    | '/tools/pdf-split'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/pdf-translator'
    | '/tools/pdf-unlock'
    | '/tools/pdf-watermark'
    | '/tools/powerpoint-to-pdf'
    | '/tools/qr-generator'
    | '/tools/rewrite-text'
    | '/tools/rotate-image'
    | '/tools/screenshot-editor'
    | '/tools/sharpen-image'
    | '/tools/subtitle-translator'
    | '/tools/summarizer'
    | '/tools/translator'
    | '/tools/voice-translator'
    | '/tools/watermark-remover'
    | '/tools/website-translator'
    | '/tools/word-to-pdf'
    | '/use-cases/$slug'
    | '/blog'
    | '/collections'
    | '/compare'
    | '/file-types'
    | '/knowledge'
    | '/questions'
    | '/tools'
    | '/use-cases'
    | '/knowledge/article/$slug'
    | '/knowledge/best/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-tools'
    | '/audio-tools'
    | '/changelog'
    | '/contact'
    | '/image-tools'
    | '/pdf-tools'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/translation-tools'
    | '/video-tools'
    | '/admin/analytics'
    | '/admin/inbox'
    | '/blog/$slug'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/compare/$slug'
    | '/file-types/$slug'
    | '/questions/$slug'
    | '/robots/txt'
    | '/tools/$slug'
    | '/tools/ai-writer'
    | '/tools/article-generator'
    | '/tools/background-changer'
    | '/tools/background-remover'
    | '/tools/blog-generator'
    | '/tools/blur-image'
    | '/tools/color-palette-generator'
    | '/tools/color-picker'
    | '/tools/crop-image'
    | '/tools/document-translator'
    | '/tools/docx-translator'
    | '/tools/excel-to-pdf'
    | '/tools/face-blur'
    | '/tools/grammar-checker'
    | '/tools/image-compressor'
    | '/tools/image-converter'
    | '/tools/image-editor'
    | '/tools/image-enhancer'
    | '/tools/image-generator'
    | '/tools/image-ocr'
    | '/tools/image-resizer'
    | '/tools/image-to-pdf'
    | '/tools/image-translator'
    | '/tools/image-upscaler'
    | '/tools/jpg-to-pdf'
    | '/tools/language-detection'
    | '/tools/large-text-translator'
    | '/tools/ocr-translator'
    | '/tools/password-generator'
    | '/tools/pdf-compress'
    | '/tools/pdf-edit'
    | '/tools/pdf-extract-pages'
    | '/tools/pdf-merge'
    | '/tools/pdf-ocr'
    | '/tools/pdf-protect'
    | '/tools/pdf-rotate'
    | '/tools/pdf-sign'
    | '/tools/pdf-split'
    | '/tools/pdf-to-jpg'
    | '/tools/pdf-to-word'
    | '/tools/pdf-translator'
    | '/tools/pdf-unlock'
    | '/tools/pdf-watermark'
    | '/tools/powerpoint-to-pdf'
    | '/tools/qr-generator'
    | '/tools/rewrite-text'
    | '/tools/rotate-image'
    | '/tools/screenshot-editor'
    | '/tools/sharpen-image'
    | '/tools/subtitle-translator'
    | '/tools/summarizer'
    | '/tools/translator'
    | '/tools/voice-translator'
    | '/tools/watermark-remover'
    | '/tools/website-translator'
    | '/tools/word-to-pdf'
    | '/use-cases/$slug'
    | '/blog/'
    | '/collections/'
    | '/compare/'
    | '/file-types/'
    | '/knowledge/'
    | '/questions/'
    | '/tools/'
    | '/use-cases/'
    | '/knowledge/article/$slug'
    | '/knowledge/best/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiToolsRoute: typeof AiToolsRoute
  AudioToolsRoute: typeof AudioToolsRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  ImageToolsRoute: typeof ImageToolsRoute
  PdfToolsRoute: typeof PdfToolsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  TranslationToolsRoute: typeof TranslationToolsRoute
  VideoToolsRoute: typeof VideoToolsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  FileTypesSlugRoute: typeof FileTypesSlugRoute
  QuestionsSlugRoute: typeof QuestionsSlugRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsAiWriterRoute: typeof ToolsAiWriterRoute
  ToolsArticleGeneratorRoute: typeof ToolsArticleGeneratorRoute
  ToolsBackgroundChangerRoute: typeof ToolsBackgroundChangerRoute
  ToolsBackgroundRemoverRoute: typeof ToolsBackgroundRemoverRoute
  ToolsBlogGeneratorRoute: typeof ToolsBlogGeneratorRoute
  ToolsBlurImageRoute: typeof ToolsBlurImageRoute
  ToolsColorPaletteGeneratorRoute: typeof ToolsColorPaletteGeneratorRoute
  ToolsColorPickerRoute: typeof ToolsColorPickerRoute
  ToolsCropImageRoute: typeof ToolsCropImageRoute
  ToolsDocumentTranslatorRoute: typeof ToolsDocumentTranslatorRoute
  ToolsDocxTranslatorRoute: typeof ToolsDocxTranslatorRoute
  ToolsExcelToPdfRoute: typeof ToolsExcelToPdfRoute
  ToolsFaceBlurRoute: typeof ToolsFaceBlurRoute
  ToolsGrammarCheckerRoute: typeof ToolsGrammarCheckerRoute
  ToolsImageCompressorRoute: typeof ToolsImageCompressorRoute
  ToolsImageConverterRoute: typeof ToolsImageConverterRoute
  ToolsImageEditorRoute: typeof ToolsImageEditorRoute
  ToolsImageEnhancerRoute: typeof ToolsImageEnhancerRoute
  ToolsImageGeneratorRoute: typeof ToolsImageGeneratorRoute
  ToolsImageOcrRoute: typeof ToolsImageOcrRoute
  ToolsImageResizerRoute: typeof ToolsImageResizerRoute
  ToolsImageToPdfRoute: typeof ToolsImageToPdfRoute
  ToolsImageTranslatorRoute: typeof ToolsImageTranslatorRoute
  ToolsImageUpscalerRoute: typeof ToolsImageUpscalerRoute
  ToolsJpgToPdfRoute: typeof ToolsJpgToPdfRoute
  ToolsLanguageDetectionRoute: typeof ToolsLanguageDetectionRoute
  ToolsLargeTextTranslatorRoute: typeof ToolsLargeTextTranslatorRoute
  ToolsOcrTranslatorRoute: typeof ToolsOcrTranslatorRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsPdfCompressRoute: typeof ToolsPdfCompressRoute
  ToolsPdfEditRoute: typeof ToolsPdfEditRoute
  ToolsPdfExtractPagesRoute: typeof ToolsPdfExtractPagesRoute
  ToolsPdfMergeRoute: typeof ToolsPdfMergeRoute
  ToolsPdfOcrRoute: typeof ToolsPdfOcrRoute
  ToolsPdfProtectRoute: typeof ToolsPdfProtectRoute
  ToolsPdfRotateRoute: typeof ToolsPdfRotateRoute
  ToolsPdfSignRoute: typeof ToolsPdfSignRoute
  ToolsPdfSplitRoute: typeof ToolsPdfSplitRoute
  ToolsPdfToJpgRoute: typeof ToolsPdfToJpgRoute
  ToolsPdfToWordRoute: typeof ToolsPdfToWordRoute
  ToolsPdfTranslatorRoute: typeof ToolsPdfTranslatorRoute
  ToolsPdfUnlockRoute: typeof ToolsPdfUnlockRoute
  ToolsPdfWatermarkRoute: typeof ToolsPdfWatermarkRoute
  ToolsPowerpointToPdfRoute: typeof ToolsPowerpointToPdfRoute
  ToolsQrGeneratorRoute: typeof ToolsQrGeneratorRoute
  ToolsRewriteTextRoute: typeof ToolsRewriteTextRoute
  ToolsRotateImageRoute: typeof ToolsRotateImageRoute
  ToolsScreenshotEditorRoute: typeof ToolsScreenshotEditorRoute
  ToolsSharpenImageRoute: typeof ToolsSharpenImageRoute
  ToolsSubtitleTranslatorRoute: typeof ToolsSubtitleTranslatorRoute
  ToolsSummarizerRoute: typeof ToolsSummarizerRoute
  ToolsTranslatorRoute: typeof ToolsTranslatorRoute
  ToolsVoiceTranslatorRoute: typeof ToolsVoiceTranslatorRoute
  ToolsWatermarkRemoverRoute: typeof ToolsWatermarkRemoverRoute
  ToolsWebsiteTranslatorRoute: typeof ToolsWebsiteTranslatorRoute
  ToolsWordToPdfRoute: typeof ToolsWordToPdfRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  FileTypesIndexRoute: typeof FileTypesIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
  KnowledgeArticleSlugRoute: typeof KnowledgeArticleSlugRoute
  KnowledgeBestSlugRoute: typeof KnowledgeBestSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-tools': {
      id: '/audio-tools'
      path: '/audio-tools'
      fullPath: '/audio-tools'
      preLoaderRoute: typeof AudioToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools': {
      id: '/image-tools'
      path: '/image-tools'
      fullPath: '/image-tools'
      preLoaderRoute: typeof ImageToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools': {
      id: '/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof PdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translation-tools': {
      id: '/translation-tools'
      path: '/translation-tools'
      fullPath: '/translation-tools'
      preLoaderRoute: typeof TranslationToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-tools': {
      id: '/video-tools'
      path: '/video-tools'
      fullPath: '/video-tools'
      preLoaderRoute: typeof VideoToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-types/': {
      id: '/file-types/'
      path: '/file-types'
      fullPath: '/file-types/'
      preLoaderRoute: typeof FileTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-types/$slug': {
      id: '/file-types/$slug'
      path: '/file-types/$slug'
      fullPath: '/file-types/$slug'
      preLoaderRoute: typeof FileTypesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$slug': {
      id: '/questions/$slug'
      path: '/questions/$slug'
      fullPath: '/questions/$slug'
      preLoaderRoute: typeof QuestionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ai-writer': {
      id: '/tools/ai-writer'
      path: '/tools/ai-writer'
      fullPath: '/tools/ai-writer'
      preLoaderRoute: typeof ToolsAiWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/article-generator': {
      id: '/tools/article-generator'
      path: '/tools/article-generator'
      fullPath: '/tools/article-generator'
      preLoaderRoute: typeof ToolsArticleGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/background-changer': {
      id: '/tools/background-changer'
      path: '/tools/background-changer'
      fullPath: '/tools/background-changer'
      preLoaderRoute: typeof ToolsBackgroundChangerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/background-remover': {
      id: '/tools/background-remover'
      path: '/tools/background-remover'
      fullPath: '/tools/background-remover'
      preLoaderRoute: typeof ToolsBackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/blog-generator': {
      id: '/tools/blog-generator'
      path: '/tools/blog-generator'
      fullPath: '/tools/blog-generator'
      preLoaderRoute: typeof ToolsBlogGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/blur-image': {
      id: '/tools/blur-image'
      path: '/tools/blur-image'
      fullPath: '/tools/blur-image'
      preLoaderRoute: typeof ToolsBlurImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-palette-generator': {
      id: '/tools/color-palette-generator'
      path: '/tools/color-palette-generator'
      fullPath: '/tools/color-palette-generator'
      preLoaderRoute: typeof ToolsColorPaletteGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/color-picker': {
      id: '/tools/color-picker'
      path: '/tools/color-picker'
      fullPath: '/tools/color-picker'
      preLoaderRoute: typeof ToolsColorPickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/crop-image': {
      id: '/tools/crop-image'
      path: '/tools/crop-image'
      fullPath: '/tools/crop-image'
      preLoaderRoute: typeof ToolsCropImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/document-translator': {
      id: '/tools/document-translator'
      path: '/tools/document-translator'
      fullPath: '/tools/document-translator'
      preLoaderRoute: typeof ToolsDocumentTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/docx-translator': {
      id: '/tools/docx-translator'
      path: '/tools/docx-translator'
      fullPath: '/tools/docx-translator'
      preLoaderRoute: typeof ToolsDocxTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/excel-to-pdf': {
      id: '/tools/excel-to-pdf'
      path: '/tools/excel-to-pdf'
      fullPath: '/tools/excel-to-pdf'
      preLoaderRoute: typeof ToolsExcelToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/face-blur': {
      id: '/tools/face-blur'
      path: '/tools/face-blur'
      fullPath: '/tools/face-blur'
      preLoaderRoute: typeof ToolsFaceBlurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/grammar-checker': {
      id: '/tools/grammar-checker'
      path: '/tools/grammar-checker'
      fullPath: '/tools/grammar-checker'
      preLoaderRoute: typeof ToolsGrammarCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-compressor': {
      id: '/tools/image-compressor'
      path: '/tools/image-compressor'
      fullPath: '/tools/image-compressor'
      preLoaderRoute: typeof ToolsImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-converter': {
      id: '/tools/image-converter'
      path: '/tools/image-converter'
      fullPath: '/tools/image-converter'
      preLoaderRoute: typeof ToolsImageConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-editor': {
      id: '/tools/image-editor'
      path: '/tools/image-editor'
      fullPath: '/tools/image-editor'
      preLoaderRoute: typeof ToolsImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-enhancer': {
      id: '/tools/image-enhancer'
      path: '/tools/image-enhancer'
      fullPath: '/tools/image-enhancer'
      preLoaderRoute: typeof ToolsImageEnhancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-generator': {
      id: '/tools/image-generator'
      path: '/tools/image-generator'
      fullPath: '/tools/image-generator'
      preLoaderRoute: typeof ToolsImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-ocr': {
      id: '/tools/image-ocr'
      path: '/tools/image-ocr'
      fullPath: '/tools/image-ocr'
      preLoaderRoute: typeof ToolsImageOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-resizer': {
      id: '/tools/image-resizer'
      path: '/tools/image-resizer'
      fullPath: '/tools/image-resizer'
      preLoaderRoute: typeof ToolsImageResizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-pdf': {
      id: '/tools/image-to-pdf'
      path: '/tools/image-to-pdf'
      fullPath: '/tools/image-to-pdf'
      preLoaderRoute: typeof ToolsImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-translator': {
      id: '/tools/image-translator'
      path: '/tools/image-translator'
      fullPath: '/tools/image-translator'
      preLoaderRoute: typeof ToolsImageTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-upscaler': {
      id: '/tools/image-upscaler'
      path: '/tools/image-upscaler'
      fullPath: '/tools/image-upscaler'
      preLoaderRoute: typeof ToolsImageUpscalerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/jpg-to-pdf': {
      id: '/tools/jpg-to-pdf'
      path: '/tools/jpg-to-pdf'
      fullPath: '/tools/jpg-to-pdf'
      preLoaderRoute: typeof ToolsJpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/language-detection': {
      id: '/tools/language-detection'
      path: '/tools/language-detection'
      fullPath: '/tools/language-detection'
      preLoaderRoute: typeof ToolsLanguageDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/large-text-translator': {
      id: '/tools/large-text-translator'
      path: '/tools/large-text-translator'
      fullPath: '/tools/large-text-translator'
      preLoaderRoute: typeof ToolsLargeTextTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ocr-translator': {
      id: '/tools/ocr-translator'
      path: '/tools/ocr-translator'
      fullPath: '/tools/ocr-translator'
      preLoaderRoute: typeof ToolsOcrTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-compress': {
      id: '/tools/pdf-compress'
      path: '/tools/pdf-compress'
      fullPath: '/tools/pdf-compress'
      preLoaderRoute: typeof ToolsPdfCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-edit': {
      id: '/tools/pdf-edit'
      path: '/tools/pdf-edit'
      fullPath: '/tools/pdf-edit'
      preLoaderRoute: typeof ToolsPdfEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-extract-pages': {
      id: '/tools/pdf-extract-pages'
      path: '/tools/pdf-extract-pages'
      fullPath: '/tools/pdf-extract-pages'
      preLoaderRoute: typeof ToolsPdfExtractPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-merge': {
      id: '/tools/pdf-merge'
      path: '/tools/pdf-merge'
      fullPath: '/tools/pdf-merge'
      preLoaderRoute: typeof ToolsPdfMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-ocr': {
      id: '/tools/pdf-ocr'
      path: '/tools/pdf-ocr'
      fullPath: '/tools/pdf-ocr'
      preLoaderRoute: typeof ToolsPdfOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-protect': {
      id: '/tools/pdf-protect'
      path: '/tools/pdf-protect'
      fullPath: '/tools/pdf-protect'
      preLoaderRoute: typeof ToolsPdfProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-rotate': {
      id: '/tools/pdf-rotate'
      path: '/tools/pdf-rotate'
      fullPath: '/tools/pdf-rotate'
      preLoaderRoute: typeof ToolsPdfRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-sign': {
      id: '/tools/pdf-sign'
      path: '/tools/pdf-sign'
      fullPath: '/tools/pdf-sign'
      preLoaderRoute: typeof ToolsPdfSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-split': {
      id: '/tools/pdf-split'
      path: '/tools/pdf-split'
      fullPath: '/tools/pdf-split'
      preLoaderRoute: typeof ToolsPdfSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-jpg': {
      id: '/tools/pdf-to-jpg'
      path: '/tools/pdf-to-jpg'
      fullPath: '/tools/pdf-to-jpg'
      preLoaderRoute: typeof ToolsPdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-word': {
      id: '/tools/pdf-to-word'
      path: '/tools/pdf-to-word'
      fullPath: '/tools/pdf-to-word'
      preLoaderRoute: typeof ToolsPdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-translator': {
      id: '/tools/pdf-translator'
      path: '/tools/pdf-translator'
      fullPath: '/tools/pdf-translator'
      preLoaderRoute: typeof ToolsPdfTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-unlock': {
      id: '/tools/pdf-unlock'
      path: '/tools/pdf-unlock'
      fullPath: '/tools/pdf-unlock'
      preLoaderRoute: typeof ToolsPdfUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-watermark': {
      id: '/tools/pdf-watermark'
      path: '/tools/pdf-watermark'
      fullPath: '/tools/pdf-watermark'
      preLoaderRoute: typeof ToolsPdfWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/powerpoint-to-pdf': {
      id: '/tools/powerpoint-to-pdf'
      path: '/tools/powerpoint-to-pdf'
      fullPath: '/tools/powerpoint-to-pdf'
      preLoaderRoute: typeof ToolsPowerpointToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr-generator': {
      id: '/tools/qr-generator'
      path: '/tools/qr-generator'
      fullPath: '/tools/qr-generator'
      preLoaderRoute: typeof ToolsQrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rewrite-text': {
      id: '/tools/rewrite-text'
      path: '/tools/rewrite-text'
      fullPath: '/tools/rewrite-text'
      preLoaderRoute: typeof ToolsRewriteTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rotate-image': {
      id: '/tools/rotate-image'
      path: '/tools/rotate-image'
      fullPath: '/tools/rotate-image'
      preLoaderRoute: typeof ToolsRotateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/screenshot-editor': {
      id: '/tools/screenshot-editor'
      path: '/tools/screenshot-editor'
      fullPath: '/tools/screenshot-editor'
      preLoaderRoute: typeof ToolsScreenshotEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sharpen-image': {
      id: '/tools/sharpen-image'
      path: '/tools/sharpen-image'
      fullPath: '/tools/sharpen-image'
      preLoaderRoute: typeof ToolsSharpenImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/subtitle-translator': {
      id: '/tools/subtitle-translator'
      path: '/tools/subtitle-translator'
      fullPath: '/tools/subtitle-translator'
      preLoaderRoute: typeof ToolsSubtitleTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/summarizer': {
      id: '/tools/summarizer'
      path: '/tools/summarizer'
      fullPath: '/tools/summarizer'
      preLoaderRoute: typeof ToolsSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/translator': {
      id: '/tools/translator'
      path: '/tools/translator'
      fullPath: '/tools/translator'
      preLoaderRoute: typeof ToolsTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/voice-translator': {
      id: '/tools/voice-translator'
      path: '/tools/voice-translator'
      fullPath: '/tools/voice-translator'
      preLoaderRoute: typeof ToolsVoiceTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/watermark-remover': {
      id: '/tools/watermark-remover'
      path: '/tools/watermark-remover'
      fullPath: '/tools/watermark-remover'
      preLoaderRoute: typeof ToolsWatermarkRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/website-translator': {
      id: '/tools/website-translator'
      path: '/tools/website-translator'
      fullPath: '/tools/website-translator'
      preLoaderRoute: typeof ToolsWebsiteTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/word-to-pdf': {
      id: '/tools/word-to-pdf'
      path: '/tools/word-to-pdf'
      fullPath: '/tools/word-to-pdf'
      preLoaderRoute: typeof ToolsWordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/use-cases'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/article/$slug': {
      id: '/knowledge/article/$slug'
      path: '/knowledge/article/$slug'
      fullPath: '/knowledge/article/$slug'
      preLoaderRoute: typeof KnowledgeArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/best/$slug': {
      id: '/knowledge/best/$slug'
      path: '/knowledge/best/$slug'
      fullPath: '/knowledge/best/$slug'
      preLoaderRoute: typeof KnowledgeBestSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiToolsRoute: AiToolsRoute,
  AudioToolsRoute: AudioToolsRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  ImageToolsRoute: ImageToolsRoute,
  PdfToolsRoute: PdfToolsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  TranslationToolsRoute: TranslationToolsRoute,
  VideoToolsRoute: VideoToolsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminInboxRoute: AdminInboxRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  FileTypesSlugRoute: FileTypesSlugRoute,
  QuestionsSlugRoute: QuestionsSlugRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsAiWriterRoute: ToolsAiWriterRoute,
  ToolsArticleGeneratorRoute: ToolsArticleGeneratorRoute,
  ToolsBackgroundChangerRoute: ToolsBackgroundChangerRoute,
  ToolsBackgroundRemoverRoute: ToolsBackgroundRemoverRoute,
  ToolsBlogGeneratorRoute: ToolsBlogGeneratorRoute,
  ToolsBlurImageRoute: ToolsBlurImageRoute,
  ToolsColorPaletteGeneratorRoute: ToolsColorPaletteGeneratorRoute,
  ToolsColorPickerRoute: ToolsColorPickerRoute,
  ToolsCropImageRoute: ToolsCropImageRoute,
  ToolsDocumentTranslatorRoute: ToolsDocumentTranslatorRoute,
  ToolsDocxTranslatorRoute: ToolsDocxTranslatorRoute,
  ToolsExcelToPdfRoute: ToolsExcelToPdfRoute,
  ToolsFaceBlurRoute: ToolsFaceBlurRoute,
  ToolsGrammarCheckerRoute: ToolsGrammarCheckerRoute,
  ToolsImageCompressorRoute: ToolsImageCompressorRoute,
  ToolsImageConverterRoute: ToolsImageConverterRoute,
  ToolsImageEditorRoute: ToolsImageEditorRoute,
  ToolsImageEnhancerRoute: ToolsImageEnhancerRoute,
  ToolsImageGeneratorRoute: ToolsImageGeneratorRoute,
  ToolsImageOcrRoute: ToolsImageOcrRoute,
  ToolsImageResizerRoute: ToolsImageResizerRoute,
  ToolsImageToPdfRoute: ToolsImageToPdfRoute,
  ToolsImageTranslatorRoute: ToolsImageTranslatorRoute,
  ToolsImageUpscalerRoute: ToolsImageUpscalerRoute,
  ToolsJpgToPdfRoute: ToolsJpgToPdfRoute,
  ToolsLanguageDetectionRoute: ToolsLanguageDetectionRoute,
  ToolsLargeTextTranslatorRoute: ToolsLargeTextTranslatorRoute,
  ToolsOcrTranslatorRoute: ToolsOcrTranslatorRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsPdfCompressRoute: ToolsPdfCompressRoute,
  ToolsPdfEditRoute: ToolsPdfEditRoute,
  ToolsPdfExtractPagesRoute: ToolsPdfExtractPagesRoute,
  ToolsPdfMergeRoute: ToolsPdfMergeRoute,
  ToolsPdfOcrRoute: ToolsPdfOcrRoute,
  ToolsPdfProtectRoute: ToolsPdfProtectRoute,
  ToolsPdfRotateRoute: ToolsPdfRotateRoute,
  ToolsPdfSignRoute: ToolsPdfSignRoute,
  ToolsPdfSplitRoute: ToolsPdfSplitRoute,
  ToolsPdfToJpgRoute: ToolsPdfToJpgRoute,
  ToolsPdfToWordRoute: ToolsPdfToWordRoute,
  ToolsPdfTranslatorRoute: ToolsPdfTranslatorRoute,
  ToolsPdfUnlockRoute: ToolsPdfUnlockRoute,
  ToolsPdfWatermarkRoute: ToolsPdfWatermarkRoute,
  ToolsPowerpointToPdfRoute: ToolsPowerpointToPdfRoute,
  ToolsQrGeneratorRoute: ToolsQrGeneratorRoute,
  ToolsRewriteTextRoute: ToolsRewriteTextRoute,
  ToolsRotateImageRoute: ToolsRotateImageRoute,
  ToolsScreenshotEditorRoute: ToolsScreenshotEditorRoute,
  ToolsSharpenImageRoute: ToolsSharpenImageRoute,
  ToolsSubtitleTranslatorRoute: ToolsSubtitleTranslatorRoute,
  ToolsSummarizerRoute: ToolsSummarizerRoute,
  ToolsTranslatorRoute: ToolsTranslatorRoute,
  ToolsVoiceTranslatorRoute: ToolsVoiceTranslatorRoute,
  ToolsWatermarkRemoverRoute: ToolsWatermarkRemoverRoute,
  ToolsWebsiteTranslatorRoute: ToolsWebsiteTranslatorRoute,
  ToolsWordToPdfRoute: ToolsWordToPdfRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  FileTypesIndexRoute: FileTypesIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
  KnowledgeArticleSlugRoute: KnowledgeArticleSlugRoute,
  KnowledgeBestSlugRoute: KnowledgeBestSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
