import { useState } from "react";
import { Paintbrush, Copy, Check, RotateCcw, Download, Plus, Trash2 } from "lucide-react";
import type { ReadyToolRuntimeDefinition } from "../types";

type GradientType = "linear" | "radial" | "conic";

function CssGradientGeneratorTool() {
  const [colors, setColors] = useState<string[]>(["#6366f1", "#ec4899", "#f59e0b"]);
  const [type, setType] = useState<GradientType>("linear");
  const [angle, setAngle] = useState(135);
  const [radialShape, setRadialShape] = useState<"circle" | "ellipse">("circle");
  const [copied, setCopied] = useState(false);

  const updateColor = (index: number, value: string) => {
    setColors((prev) => prev.map((c, i) => (i === index ? value : c)));
  };

  const addColor = () => setColors((prev) => [...prev, "#ffffff"]);
  const removeColor = (index: number) => {
    if (colors.length <= 2) return;
    setColors((prev) => prev.filter((_, i) => i !== index));
  };

  const stops = colors
    .map((color, i) => `${color} ${Math.round((i / (colors.length - 1)) * 100)}%`)
    .join(", ");

  const css =
    type === "linear"
      ? `linear-gradient(${angle}deg, ${stops})`
      : type === "radial"
        ? `radial-gradient(${radialShape}, ${stops})`
        : `conic-gradient(from ${angle}deg at 50% 50%, ${stops})`;

  const handleCopy = () => {
    navigator.clipboard.writeText(`background: ${css};`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const cssText = `/* Generated by Flixo CSS Gradient Generator */\n.gradient {\n  background: ${css};\n}\n`;
    const blob = new Blob([cssText], { type: "text/css;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "gradient.css";
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleReset = () => {
    setColors(["#6366f1", "#ec4899"]);
    setType("linear");
    setAngle(135);
    setRadialShape("circle");
    setCopied(false);
  };

  return (
    <div className="rounded-3xl border border-border bg-card p-6 md:p-8 space-y-6">
      <div
        className="h-48 rounded-2xl border border-border"
        style={{ background: css }}
        aria-label="Gradient preview"
        role="img"
      />

      <div className="grid gap-6 md:grid-cols-2">
        <div className="space-y-4">
          <div className="space-y-2">
            <label className="text-sm font-semibold text-foreground">Gradient type</label>
            <div className="flex rounded-xl border border-border p-1 bg-background">
              {(["linear", "radial", "conic"] as GradientType[]).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setType(t)}
                  className={`flex-1 px-3 py-1.5 text-xs font-semibold rounded-lg capitalize transition-colors ${
                    type === t
                      ? "bg-primary text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {(type === "linear" || type === "conic") && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-sm font-semibold text-foreground">Angle</label>
                <span className="text-xs font-mono text-muted-foreground">{angle}°</span>
              </div>
              <input
                type="range"
                min={0}
                max={360}
                value={angle}
                onChange={(e) => setAngle(Number(e.target.value))}
                className="w-full accent-primary"
              />
            </div>
          )}

          {type === "radial" && (
            <div className="space-y-2">
              <label className="text-sm font-semibold text-foreground">Shape</label>
              <div className="flex rounded-xl border border-border p-1 bg-background">
                {(["circle", "ellipse"] as const).map((s) => (
                  <button
                    key={s}
                    type="button"
                    onClick={() => setRadialShape(s)}
                    className={`flex-1 px-3 py-1.5 text-xs font-semibold rounded-lg capitalize transition-colors ${
                      radialShape === s
                        ? "bg-primary text-primary-foreground"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          )}

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-sm font-semibold text-foreground">Color stops</label>
              <button
                type="button"
                onClick={addColor}
                className="inline-flex items-center gap-1 text-xs text-primary hover:underline font-medium"
              >
                <Plus className="size-3.5" />
                Add stop
              </button>
            </div>
            <div className="space-y-2">
              {colors.map((color, i) => (
                <div key={i} className="flex items-center gap-2">
                  <input
                    type="color"
                    value={color}
                    onChange={(e) => updateColor(i, e.target.value)}
                    className="size-9 shrink-0 rounded-lg border border-border bg-background cursor-pointer"
                    aria-label={`Color stop ${i + 1}`}
                  />
                  <input
                    type="text"
                    value={color}
                    onChange={(e) => updateColor(i, e.target.value)}
                    className="flex-1 rounded-lg border border-border bg-background px-3 py-2 font-mono text-xs text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                  <button
                    type="button"
                    onClick={() => removeColor(i)}
                    disabled={colors.length <= 2}
                    className="text-muted-foreground hover:text-destructive disabled:opacity-30"
                  >
                    <Trash2 className="size-4" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <label className="text-sm font-semibold text-foreground">CSS Output</label>
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-1 text-xs text-primary hover:underline font-medium"
              >
                {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                {copied ? "Copied" : "Copy"}
              </button>
              <button
                type="button"
                onClick={handleDownload}
                className="inline-flex items-center gap-1 text-xs text-primary hover:underline font-medium"
              >
                <Download className="size-3.5" />
                Download
              </button>
              <button
                type="button"
                onClick={handleReset}
                className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-destructive"
              >
                <RotateCcw className="size-3.5" />
                Reset
              </button>
            </div>
          </div>
          <pre className="rounded-2xl border border-border bg-background p-4 font-mono text-xs text-foreground overflow-auto whitespace-pre-wrap break-all">
            {`background: ${css};`}
          </pre>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <Paintbrush className="size-4" />
            <span>Adjust stops, angle, and shape to preview live.</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export const CssGradientGeneratorRuntime: ReadyToolRuntimeDefinition = {
  toolId: "css-gradient-generator",
  slug: "css-gradient-generator",
  categoryId: "developer",
  icon: Paintbrush,
  component: CssGradientGeneratorTool,
  layoutDescription:
    "Design linear, radial, and conic CSS gradients visually with color stops, angle, and shape controls.",
};
