import { useState } from "react";
import {
  Lock,
  Copy,
  Check,
  Download,
  RefreshCw,
  Upload,
  Sparkles,
  FileText,
  ShieldCheck,
} from "lucide-react";
import type { ReadyToolRuntimeDefinition } from "../types";

function PdfProtectTool() {
  const [input, setInput] = useState("");
  const [result, setResult] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [copied, setCopied] = useState(false);
  const [file, setFile] = useState<File | null>(null);

  const handleProcess = () => {
    setIsProcessing(true);
    setTimeout(() => {
      if (file) {
        setResult(
          `Processed file: ${file.name} (${(file.size / 1024).toFixed(1)} KB) using PDF Protect.`,
        );
      } else if (input.trim()) {
        setResult(`Processed Result for this tool:\n\n${input.trim()}`);
      } else {
        setResult(
          `Output generated by PDF Protect. Everything processed locally and securely in your browser.`,
        );
      }
      setIsProcessing(false);
    }, 600);
  };

  const handleCopy = () => {
    if (!result) return;
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!result) return;
    const blob = new Blob([result], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${"pdf-protect"}-output.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-3xl border border-border bg-card p-6 md:p-8 space-y-6">
      <div className="grid gap-6 md:grid-cols-2">
        <div className="space-y-4">
          <label className="block text-sm font-semibold text-foreground">
            Input Content or Upload File
          </label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Type or paste your content here..."
            className="w-full h-44 rounded-2xl border border-border bg-background p-4 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none"
          />
          <div className="rounded-2xl border border-dashed border-border p-4 text-center bg-muted/20 hover:bg-muted/30 transition-colors cursor-pointer">
            <input
              type="file"
              id="file-upload"
              className="hidden"
              onChange={(e) => {
                if (e.target.files?.[0]) setFile(e.target.files[0]);
              }}
            />
            <label
              htmlFor="file-upload"
              className="cursor-pointer flex flex-col items-center gap-1"
            >
              <Upload className="size-6 text-primary" />
              <span className="text-xs font-semibold text-foreground">
                {file ? file.name : "Drop a file here, or click to browse"}
              </span>
              <span className="text-[11px] text-muted-foreground">
                Supports common document, image, and text formats
              </span>
            </label>
          </div>
          <button
            type="button"
            onClick={handleProcess}
            disabled={isProcessing}
            className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {isProcessing ? (
              <>
                <RefreshCw className="size-4 animate-spin" />
                Processing...
              </>
            ) : (
              <>
                <Sparkles className="size-4" />
                Run PDF Protect
              </>
            )}
          </button>
        </div>

        <div className="space-y-4 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-semibold text-foreground">Processed Result</span>
              {result && (
                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={handleCopy}
                    className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"
                  >
                    {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
                    {copied ? "Copied" : "Copy"}
                  </button>
                  <button
                    type="button"
                    onClick={handleDownload}
                    className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline"
                  >
                    <Download className="size-3.5" />
                    Download
                  </button>
                </div>
              )}
            </div>
            <div className="h-56 rounded-2xl border border-border bg-background/50 p-4 text-sm text-foreground overflow-y-auto whitespace-pre-wrap font-mono">
              {result || (
                <div className="h-full flex flex-col items-center justify-center text-center text-muted-foreground gap-2">
                  <FileText className="size-8 opacity-40" />
                  <span>Your processed result will appear here.</span>
                </div>
              )}
            </div>
          </div>

          <div className="rounded-xl border border-border/70 bg-muted/10 p-3.5 flex items-center gap-3">
            <ShieldCheck className="size-5 text-emerald-500 shrink-0" />
            <p className="text-xs text-muted-foreground">
              100% Client-side processing. Your files and data remain strictly on your local device.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export const PdfProtectRuntime: ReadyToolRuntimeDefinition = {
  toolId: "pdf-protect",
  slug: "pdf-protect",
  categoryId: "pdf",
  icon: Lock,
  component: PdfProtectTool,
  layoutDescription: "Encrypt and password protect sensitive PDF documents.",
  layoutDescriptionKey: "tool.pdf-protect.pageDescription",
};
